### ISSUE TITLE
RFC: Move work related to Controller concept in a new module (pippo-controller)

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#107]
I created a new branch [controller_module](https://github.com/decebals/pippo/tree/controller_module) when I move the `Controller` concept in a new module `pippo-controller`.
I see now that I made a mistake - I created this branch not from `master` (from `cookie_session` branch) - but I can fix this very easy.
I created some extensions like: `ControllerApplication extends Application`, `ControllerRouter extends Router`, ... Fill free to propose other names or other approaches.
We have a little problem with `MetricsRouteContext` from `pippo-metrics` but I think that we can fix it. The problem is that in this class we have:
```java
if (handler instanceof ControllerHandler) {
    ControllerHandler controllerHandler = (ControllerHandler) handler;
    method = controllerHandler.getMethod();
}
```
and I don't want to add a dependency to `pippo-controller` module for this reason. I think that we can resolve this problem with reflection.

**Comment by gitblit** [comment]
I have some ideas on this.  I'll PM you.
