### ISSUE TITLE
Request.getBoby() may be error-prone

### ISSUE THREAD

**Issue by richdyang** [decebals/pippo#111]
First, it converts the input stream using the default charset. So if I post a data using application/octet-stream with a charset different from the default charset, some characters will be impossible for reverse conversion.

Another thing is that there is some time when I really want to process stream-based binary data, but Request don't have the option.

Please consider exposing the stream to developers.

**Comment by decebals** [comment]
It was an issue in IoUtils.copy. I added UTF_8 as charset. Now. I think that Request.getBody() it's ok.
Related to process stream-based binary data we have already Response.getHttpServletRequest().getInputStream(). I don't know if getInputStream() is so common as getBody() to deserve a helper/wrapper method in Response.

**Comment by decebals** [comment]
Is it ok for you? If yes, please close the issue.
