### ISSUE TITLE
Any plan to support route specific interceptor (aka filter)

### ISSUE THREAD

**Issue by nchiring** [decebals/pippo#112]
Hi,

   I have been watching this repo for some time now. Good development so far! 
I m planning to build a project using this framework. However, I have certain use cases for interceptor.
Any plan to support it?

**Comment by gitblit** [comment]
In the core project we have [filters](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Application.java#L257) and we have [pre- and post- request/response processing hooks](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Application.java#L323).

Do those satisfy your need or do you mean DI interceptors?  Can you define what *interceptor* means?

**Comment by nchiring** [comment]
Currently, I am interested in Around filter mostly -  
1)  request/response cycle AOP interceptor  e.g. @Secure ( This is somewhat similar to [@Timed](https://github.com/decebals/pippo/blob/master/pippo-metrics/src/main/java/ro/pippo/metrics/Timed.java) , however, this interceptor class should be covered by DI ) . I may be wrong, but  pre -post hooks appear to be request/response agnostic( global scoped)
            2) It should be to possible to do   - 
                      ThreadLocal.set() ; 
                      routeHandle(); 
                      ThreadLocal.clear()
              Applicaltion#ALL() doesn't look like meeting this need.
Real examples,  In Ninja framework - [http://www.ninjaframework.org/apidocs/ninja/Filter.html](http://www.ninjaframework.org/apidocs/ninja/Filter.html)
                  SparkJava - [http://sparkjava.com/documentation.html#filters](http://sparkjava.com/documentation.html#filters)

**Comment by gitblit** [comment]
Ninja directly integrates Guice; Pippo-core does not integrate a DI container so it does not support AOP or DI but we do have some basic examples of how you can integrate DI in your project:

- https://github.com/decebals/pippo/tree/master/pippo-demo/pippo-demo-guice
- https://github.com/decebals/pippo/tree/master/pippo-demo/pippo-demo-spring

The pre- and post- hooks are global for all requests.  They are generally useful for metrics, logging, setup, or cleanup.

Pippo does support the concept of `before` and `after` filters for routes.  This is achieved by explicit route ordering and the `ALL` registration.

In the following example, `myInterceptor` and `cleanup` are called for every request that matches the regex `/secure/.*`.  The `runAsFinally` call ensures that the cleanup route is executed even if one of the other routes in the matched route chain throws an exception.

```java
  ALL("/secure/.*", myInterceptor);
  GET("/secure/.*", getSomething);
  POST("/secure/.*", postSomething);
  ALL("/secure/.*", cleanup).runAsFinally();
```

**Comment by nchiring** [comment]
Thanks James. I shall go through your examples.
 Agree, Ninja leverages guice directly. Unfortunately, in my case I am trying to use dagger 2.0 as DI (yeah, why is another story)

**Comment by gitblit** [comment]
I used Dagger 1.x in a webapp and I wouldn't do it again.  Dagger is a fine DI solution if you have a JSE app.  As soon as you want to run your Dagger-based app on a JEE container you are likely to have trouble as Dagger does not play nice with CDI.  Guice has the same issue, actually, but Guice has an advantage over Dagger here: it supports it's own annotations in addition to javax.inject.  For better or worse, CDI basically owns the javax.inject namespace now.  Keep that in mind as you move forward.

**Comment by decebals** [comment]
Have you solved the problem? Can I help you?

**Comment by gitblit** [comment]
@decebals I think it's fair to close this issue.

**Comment by decebals** [comment]
@nchiring I put a snapshot that resolve #117. We introduced the `ControllerFactory` interface that can instantiate a `Controller` object. For example, The module [pippo-spring]({{ site.codeurl }}/pippo-spring) contains [SpringControllerFactory]({{ site.codeurl }}/pippo-spring/src/main/java/ro/pippo/spring/SpringControllerFactory.java) that it's a `ControllerFactory` implementation that delegates to the Spring container to instantiate a given `Controller` class. This allows for the instance to be configured via dependency injection (all Spring annotations are valid, AOP, ...).
Maybe the new concept can help you to implement your interceptors.
