### ISSUE TITLE
Reverse Routing  - ContactsController - ClassCastException

### ISSUE THREAD

**Issue by nchiring** [decebals/pippo#113]
Using pippo-controller 0.5.0-SNAPSHOT version and hitting 

Caused by: java.lang.ClassCastException: ro.pippo.core.route.DefaultRouter cannot be cast to ro.pippo.controller.ControllerRouter
	at demo.controller.ContactsController.uriFor(ContactsController.java:44)

My investigation points the problem to ro.pippo.controller.ControllerApplication.
The problem is resolved if I override the following methods, 

```java
public class ControllerApplication extends Application {
   private DefaultControllerRouter router;
  //other methods as they are
  @Override
	public Router getRouter() {
		if (router == null) {
            router = new DefaultControllerRouter();
        }

        return router;
	}

	@Override
	public void setRouter(Router router) {
		super.setRouter(router);
	}

} 

```

**Comment by gitblit** [comment]
Good catch. That was a side-effect of some recent refactoring.
