### ISSUE TITLE
RouteDispatcher ignores filterPath

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#115]
In `RouterDispatcher.onRouteDispatch()` the value for `requestPath` is not correct calculated. The correct calculation is in `PippoFilter.getRelativePath()` that by the way is not used anymore.

**Comment by gitblit** [comment]
The issue was serving Pippo on a non-root filter path?

BTW, I would have named it `applicationPath` or `pippoPath` not `filterPath` - which implies use of `PippoFilter`.  Did `PippoServlet` also need to be updated?

**Comment by decebals** [comment]
Yes. The issue occurs when you map `PippoFilter` (in `web.xml` in particular) on an non-root path (for example `/rest/*`). The `PippoServlet` is not affected by this issue.
Also I moved `setFilterPath()` from `PippoFilter` in `WebServer` because it's hard to transform a filterPath (for example /rest/*) in a canonical format (rest/).
In what file do you want to rename variable `filterPath`?

if you see a clearer resolution of the problem please let me know.

**Comment by decebals** [comment]
You have right, my solution doesn't work for `PippoServlet` because `Response.setRelativePath()` is not called. I don't find a nice solution for both (Servlet and Filter). Before my commit we had duplication code (related to relative path in `PippoFilter` and `RouteDispatcher.onRouteDispatch()`). I will rethink my solution. Maybe a (Url)PathUtils class with static methods for different path types is a solution.

**Comment by gitblit** [comment]
I think we rushed on implementation and release of 0.4.1 without thinking this completely through.
`PippoServlet` has this problem too - the analog would be *servletPath* instead of *filterPath*.

The issue gets larger when you consider templates....
```
${contextPath}/${pippoPath}/item/${id}
```

... and then, of course, reverse-routing.  At the moment, I think we are in poor shape for serving Pippo from a subpath of the context path.

**Comment by decebals** [comment]
I released 0.4.1 for #113.

**Comment by gitblit** [comment]
Sorry, I was mistaken.  When you get a chance, take a look at #116.  I think that covers all the cases.

**Comment by decebals** [comment]
Resolved by #116.

**Comment by decebals** [comment]
Are you OK with a new release (0.4.2) that should contain this fix?

**Comment by gitblit** [comment]
Absolutely!
