### ISSUE TITLE
pippo-spring @Autowired is not supported

### ISSUE THREAD

**Issue by balamaci** [decebals/pippo#117]
@Autowired fields do not get injected, only @Inject is considered.

**Comment by balamaci** [comment]
Also @Value("${mail.from}") annotations are not supported

**Comment by decebals** [comment]
The actual implementation of pippo-spring probably is not the best but I don't see how we can deal with custom annotation (@Value, @Autowired). 
I don't see an easy solution. Maybe it's time to revitalized https://github.com/gitblit/pippo/commit/ea1cbfee621976e85006024cbc51b0b84c0c9ac5

**Comment by gitblit** [comment]
Injecting based on `@Inject` or `@Autowired` is easy enough to do.  That commit does include `@Autowired` support.  That, at least, should be extracted and applied.

I'm not familiar with `@Value`.

**Comment by gitblit** [comment]
After a quick Google search, I am now familiar.  I think the take-away on Pippo's Spring IoC implementation is that it's not *really* Spring IoC.  Right @decebals ?  It's a home-brewed injection mechanism using Spring contexts, Spring annotations, and custom reflection.  Now I say that not being a Spring user, I prefer Guice.  So maybe I am wrong - but it has always looked like DIY injection to me.

**Comment by decebals** [comment]
@gitblit Sure. I am not happy with the current implementation but I don't have other idea. I will dig on internet to see if I will find a valuable idea, a something more general.

**Comment by decebals** [comment]
I created a local branch to validate another approach. My idea is to let `Spring` to instantiate the Controller object and in this mode we can resolve all annotations. For this reason we must define programmaticaly the `Controller` as a Spring bean. In `PF4J-Spring` integration I used this approach via [ExtensionsInjector](https://github.com/decebals/pf4j-spring/blob/master/src/main/java/ro/fortsoft/pf4j/spring/ExtensionsInjector.java).
I don't know if I can do the same thing in Guice.

**Comment by decebals** [comment]
@balamaci , @gitblit What you say about https://github.com/decebals/pippo/tree/spring? The implementation it's very light and we resolve all cases.
I updated `pippo-demo-spring` to reflect the last modification.
I don't know if we can apply the same approach for a `pippo-guice` integration.

**Comment by decebals** [comment]
I will add some details.

In your [ControllerApplication](https://github.com/decebals/pippo/blob/spring/pippo-demo/pippo-demo-spring/src/main/java/ro/pippo/demo/spring/SpringApplication.java) you must add this line in `onInit` method:
```java
        // registering SpringControllerFactory
//        setInstanceProvider(new SpringControllerFactory(applicationContext, false));
        setControllerFactory(new SpringControllerFactory(applicationContext));
``` 

The main component is [SpringControllerFactory](https://github.com/decebals/pippo/blob/spring/pippo-spring/src/main/java/ro/pippo/spring/SpringControllerFactory.java).
This class has two constructors: with and without `autoRegistering`. If `autoRegistering` flag is set on `true` then if Spring doesn't contain a bean for a controller class, `SpringControllerFactory` will create and register a `BeanDefinition`.
If you want to modify the default bean definition of the `Controller` you must override `createBeanDefinition` method.

**Comment by gitblit** [comment]
This looks like a step in the right direction.  I still think IoC can be further improved but I don't have any concrete recommendations right now.

**Comment by decebals** [comment]
@gitblit I pushed a new version of `pippo-guice` (only one class `GuiceControllerFactory` in branch `spring`) but I don't use `Guice` so I don't know if the implementation is OK (the demo is functional). Please let me know if it's OK for you.

**Comment by gitblit** [comment]
Yup.  That looks fine.

**Comment by decebals** [comment]
Updated [Spring](http://www.pippo.ro/mod/spring.html) and [Guice](http://www.pippo.ro/mod/guice.html) sections on the documentation site.
