### ISSUE TITLE
Changelog document

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#118]
> Maybe we should have a changelog? @gitblit 

Very good idea. I think that a changelog is a must have.
In the past I tried to use github [Releases](https://github.com/blog/1547-release-your-software) but without much success. Do you prefer the automatic approach via github Releases or the manual approach? If you prefer the manual approach who do you see the implementation (a changelog file, ...).

**Comment by decebals** [comment]
> I generally don't use the Releases feature either.

> For Gitblit I maintain a YAMLish changelog file. I do that so I can build the site from the embedded documentation and generate an HTML changelog. But that is a homegrown, complicated solution.

> I recommend a simple file. Probably Markdown. It makes the most sense to have that file with the documentation sources. I'm wondering if it's a good idea to keep pippo-site separate from pippo? @gitblit

**Comment by decebals** [comment]
I am ok with a CHANGELOG,md file in pippo repository. Maybe http://keepachangelog.com help us.

Initial pippo-site was a branch on the pippo repository but I moved it in a new repository because I thought that in this mode, in the future we can accept more easy new collaborators on the documentation site (different collaborator for sources and documentation).

**Comment by gitblit** [comment]
Yes.  Let's take that approach.  I can start one, if you like.

**Comment by decebals** [comment]
Sure. Thanks :+1:

**Comment by gitblit** [comment]
I've started a changelog:
https://github.com/decebals/pippo/blob/master/CHANGELOG.md

The 0.4.0 release needs improving but I am out of time for the day.

**Comment by decebals** [comment]
It's a good start.
