### ISSUE TITLE
FileResourceHandler usage is not self evident

### ISSUE THREAD

**Issue by balamaci** [decebals/pippo#120]
FileResourceHandler constructor is taking two parameters "url" and "directory"
https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/route/FileResourceHandler.java

making it confusing to use it like:
GET("/url", new FileResourceHandler("url", "directory")); 

it's intended to be used with:
GET(new FileResourceHandler("url", "directory"));

**Comment by decebals** [comment]
I am ok with what you say. All static resource handlers are based on `StaticResourceHandler`. In the [constructor](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/route/StaticResourceHandler.java#L47) of this class we create an uriPattern using the urlPath: `this.uriPattern = String.format("/%s/{%s: .*}", getNormalizedPath(urlPath), PATH_PARAMETER);` Method `getUriPattern` is used in [Application](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Application.java#L226). I don't know how we can eliminate this confusion.
All I see is a check in `GET("/url", RouteHandler)` in this form:
```
if (routeHandler instanceof StaticResourceHandler) {
    __error("Please use 'GET(StaticResourceHandler resourceHandler)'");
}
```

Maybe someone has other resolution.

**Comment by gitblit** [comment]
I propose eliminating the duplicate handler check [from here](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Application.java#L221)

... and then something like this:
```java
public Route addWebjarResourceHandler() {
    return addWebjarResourceHandler("/webjars");
}

public Route addWebjarResourceHandler(String basePath) {
    return GET(new WebjarsResourceHandler(basePath));
}

public Route addPublicResourceHandler() {
    return addPublicResourceHandler("/public");
}

public Route addPublicResourceHandler(String basePath) {
    return GET(new PublicResourceHandler(basePath));
}

public Route addFileResourceHandler(String basePath, File directory) {
    return GET(new FileResourceHandler(basePath, directory));
}
```

**Comment by gitblit** [comment]
Yeah, ok.  Maybe throwing `PippoRuntimeException` in `GET(String, RouteHandler)` is necessary to prevent it.

**Comment by gitblit** [comment]
The reason the resource handlers are different than the others is because they specify a fixed url parameter named `path` and the value extraction regex.  Is there a better alternative?

**Comment by decebals** [comment]
It's ok, I explained above why `StaticResourceHandler` takes in constructor an `urlPath` as parameter.

**Comment by balamaci** [comment]
Yes, the missing javadoc might have caused more confusion than what this issue might have deserved.

**Comment by decebals** [comment]
Please use the new methods `addXXXResourceRoute()` (`addPublicResourceRoute()`, `addFileResourceRoute()`, `addClasspathResourceRoute()`, `addWebjarsResourceRoute()`)
