### ISSUE TITLE
Refactor TemplateEngine and move Reponse.render() implementation to DefaultRouteContext

### ISSUE THREAD

**Issue by gitblit** [decebals/pippo#123]
I have two more unreleased modules that I wrote for Ninja.  One of them is full [Thymeleaf](http://www.thymeleaf.org) integration.

Thymeleaf, favored by Spring, has some compelling features.  Generally I have found it 2x slower than most other template engines, but it's Wicket-ish, being an XHTML-based engine, and validates the document structure.  Plus, the Thymeleaf devs have been working on version 3 which apparently boosts performance and might make it more competitive with the likes of Pebble, Freemarker, & Trimou.

In order to have **full** integration you need to provide `HttpServletRequest`, `HttpServletResponse`, & `ServletContext` to the engine at rendering time.  Without full integration, Thymeleaf is not as appealing.

If you are open to a little refactoring/redesigning of the internal interfaces, then I can bring this integration to Pippo.

I'm testing the waters before devoting any energy to this topic.

**Comment by decebals** [comment]
For now I don't have a favorite template engine. I do my job with freemarker. I know nothing about Thymeleaf but if your intention is to use this template engine we can try to integrate it in pippo.
I am not sure that we must move Response.render() in DefaultRouteContext. Maybe we can use Response.get() and Request.get() for a first implementation. I know your opinion about all business in a big RouteContext and without Request, Response (only with HttpServletRequest, HttpServletResponse) and I try to analyze this variant. Now I see RouteContext as a container for useful entities like Request,Response and some shortcuts for Request.metho Response.method but this is another story.

**Comment by gitblit** [comment]
> but if your intention is to use this template engine

I'm undecided, but choices are always good.

> Maybe we can use Response.get() and Request.get() for a first implementation. 

You know I loathe static accessors BUT this seems reasonable... for a first implementation.

> Now I see RouteContext as a container for useful entities like Request,Response and some shortcuts

This is how I see it too.  My thought was something like this `TemplateEngine.renderResource(String, Map<String, Object>, RouteContext)` or maybe `TemplateEngine.renderResource(String, RouteContext)` or maybe `TemplateEngine.renderResource(String, Map<String, Object>, Request, Response)` but I haven't spent any time on it.

Maybe the static accessor is the best approach.  In any event, I'll move forward with that plan and see if I hit any roadblocks.

**Comment by gitblit** [comment]
Pebble is so good that I can't imagine ditching it.  Closing issue.

**Comment by Wavesonics** [comment]
Did anyone ever get Thymeleaf implemented in Pippo?

**Comment by rygel** [comment]
As far as I know Thymeleaf did not get implemented. I guess it is important to you?
