### ISSUE TITLE
Parameter value is not url encoded by default

### ISSUE THREAD

**Issue by balamaci** [decebals/pippo#124]
I don't know if it's intentional or not, it seems in the sources there is a comment.
https://github.com/decebals/pippo/blob/cbb8863bb0dbee1f4154a90774144a3e2dbdeeb6/pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java#L407

Maybe I'm used to wicket but I was expecting the value to be automatically encoded.

**Comment by gitblit** [comment]
@decebals Why not just use `URLEncoder` instead of roll-your-own?

**Comment by decebals** [comment]
@gitblit My first intention was to use `URLEncoder` but I read some unfavorable comments (for example http://stackoverflow.com/questions/10786042/java-url-encoding-of-query-string-parameters). 
Sure I have no problem to use `URLEncoder`. 
I remarked some differences. For example "Decebal Suiu" is encoded "Decebal+Suiu" with `URLEncoder` and "Decebal%20Suiu" with my function.
Please tell me if you want to use `URLEncoder` to make the change.

**Comment by decebals** [comment]
A nice article about UrlEncoding is http://blog.lunatech.com/2009/02/03/what-every-web-developer-must-know-about-url-encoding.

**Comment by gitblit** [comment]
Totally agree.  I'm familiar with that article which is why I am wary of roll-your-own solutions for encoding. I think the best solution is to add a proven Apache dependency with proper encoding utils but that is a slippery slope and breaks our nice claim that `Pippo-Core` has a single dependency - logging - and that's it.

**Comment by decebals** [comment]
Added a notice in [Reverse routing](http://www.pippo.ro/doc/reverse-routing.html) section on the documentation site.
