### ISSUE TITLE
Java 8 reloaded

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#139]
I wish to review the Pippo switch to J8.
The idea is not new, we have some discussions on this theme in #41 and #43. We have some benefits : __Lambda__ (short route handler registration), __Optional__ and maybe more. The main problem is if we want to move pippo to J8 or to create a new branch (or maybe pippo2) and when we start work on this feature,
I am waiting opinions.

**Comment by gitblit** [comment]
Java 8. Its a no-brainer.  I don't think we should go for Pippo 2 already as we haven't even hit 1.0. I have always run on J8 exclusively and switching Pippo to J8 will allow me to upstream improvements to the controller package and make my Fathom-Pippo integration thinner. That's a win for everyone.

I really like Optional... In Guava. ☺ J8 optional is a little inferior but not too bad.

Anyway, I'm pro J8 and am ready for the switch yesterday.

**Comment by decebals** [comment]
Done
