### ISSUE TITLE
Web server tuning

### ISSUE THREAD

**Issue by gustavogalvan** [decebals/pippo#147]
Make options (threads, buffer size, etc.) for each webserver accesible from settings files. This is specially usefull for Undertow, where speed varies with response size and buffer size needs to be configured.

**Comment by decebals** [comment]
I pushed a possible implementation. Maybe it's not the best but it's work.

You must add this line in your ApplicationLauncher before `pippo.start();`
```java
((UndertowServer) pippo.getServer()).getSettings().setBufferSize(10 * 1024);
```

Any comment is welcome.

**Comment by gustavogalvan** [comment]
Seems ok for me.
I downloaded the branch "server-settings" but doesn't compile jetty & undertow modules:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project pippo-jetty: Compilation failure: Compilation failure:
[ERROR] bootstrap class path not set in conjunction with -source 1.7
[ERROR] /home/gustavo/Proyectos/Pippo/pippo/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java:[44,50] error: type AbstractWebServer does not take parameters
[ERROR] /home/gustavo/Proyectos/Pippo/pippo/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java:[50,4] error: method does not override or implement a method from a supertype
[ERROR] /home/gustavo/Proyectos/Pippo/pippo/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java:[55,32] error: cannot find symbol

**Comment by decebals** [comment]
I cannot reproduce your error. I compile the project from command line (maven) and also from IDE with both java 1.7 (17.0_25) and 1.8 (1.8.0_40) without errors. Maybe another user can confirm that it's an issue on compilation.

**Comment by gustavogalvan** [comment]
Sorry ... my bad. Maven was using a pippo-core cached version. Compilation is OK, thanks !

**Comment by decebals** [comment]
No problem. 
I see here some problems with the default settings.
For example at https://github.com/decebals/pippo/commit/4cf1353c7d168843b02e97a551ab4ce852b73716#diff-461ae40e92bd3b5964439e29c7c0fc47R109 I don't know if that check (bufferSize> 0) is the best solution. We don't know the default value so we can't know if the user made some custom settings or not.

**Comment by gustavogalvan** [comment]
https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/Undertow.java

builder() calculate default values for: directBuffers, bufferSize and buffersPerRegion. Next, the programmer has the responsability for changing values (or not).

**Comment by decebals** [comment]
Sure, but when a `UndertowServer` is instantiated then a default `UndertowSettings` is created (via `createDefaultSettings` method). The problem is that by default you have `bufferSize = 0` and you are forced to check if the user modified this value or not when you create the Undertow instance. Only if `bufferSize > 0` (touched/modified setting) you must set that value in `Undertow.Builder` class via `setBufferSize` method. All I want to say is that the convention with `buffer = 0` and `if (bufferSize > 0)` is a little fragile.
I don't know if I am clear enough.

**Comment by gustavogalvan** [comment]
Sorry, I've misunderstood you. I don't see problems using 0 as "don't touch this". 
Moreover, there are more values to adjust ... so as you are doing that, could you add more? like setBuffersPerRegion, setIoThreads, setWorkerThreads and setDirectBuffers

**Comment by gustavogalvan** [comment]
- all are Int but setDirectBuffers is Boolean -

**Comment by decebals** [comment]
Sure. You can put any Undertow setting. If you want more settings in `UndertowSettings` please submit a Pull Request.

**Comment by decebals** [comment]
@gitblit What you say, is it ok my approach?

**Comment by gustavogalvan** [comment]
It's ok for me. At least it is a good starting point because solves a performance issue.

**Comment by gitblit** [comment]
Looks good. Being able to tune from `PippoSettings` would be a plus: `undertow.bufferSize`.

**Comment by decebals** [comment]
Done. You can put `undertow.bufferSize = 1024` in your `application.properties`.
