### ISSUE TITLE
Rhythm template engine

### ISSUE THREAD

**Issue by danjee** [decebals/pippo#153]
As I saw on their site the Rhythm template engine seems to have good performance:
"Being different from dynamic engines like Velocity and FreeMarker, Rythm is a static typed engine and compile your template source into java byte code, and thus very fast. Based on the result of this benchmark test, Rythm is one of the fastest template engines in Java world."

I want to know if it will worth the effort of integrating it.

**Comment by gitblit** [comment]
> I want to know if it will worth the effort of integrating it.

Probably the only way to know if it is worth the effort is to do it.  Rhythm has been around for a few years and has not caught-on, for whatever reason. I'm not saying it's bad - but I don't run across it in the wild.

You might find [this](https://github.com/mbosecke/template-benchmark) interesting.  It's not comprehensive across all available engines, but it generally matches my observations the last time I compared.

**Comment by danjee** [comment]
Yes, this can be done. I will send a PR after my changes are completed
