### ISSUE TITLE
Webjars version

### ISSUE THREAD

**Issue by danjee** [decebals/pippo#164]
A nice idea from wicket-bootstrap implementation of webjars was to use the `current` to get the latest version of the webjar, so if you modify the pom.xml to get other dependecy you shouldn't modify all the html or templates. Of course this should be optional and if the user wants to use the fixed version string the scripts should be loaded.

**Comment by decebals** [comment]
I like the idea but I see some improvements (I don't know if it's technical possible or if add some value).
For example now we do:
```
<link href="${webjarsAt('bootstrap/3.3.1/css/bootstrap.min.css')}" rel="stylesheet">
<script src="${webjarsAt('jquery/1.11.1/jquery.min.js')}"></script>
```
You propose:
```
<link href="${webjarsAt('bootstrap/current/css/bootstrap.min.css')}" rel="stylesheet">
<script src="${webjarsAt('jquery/current/jquery.min.js')}"></script>
```
I prefer a very aggressive approach as:
```
<link href="${webjarsAt('bootstrap.min.css')}" rel="stylesheet">
<script src="${webjarsAt('jquery.min.js')}"></script>
```
or
```
<link href="${webjarsAt('css/bootstrap.min.css')}" rel="stylesheet">
<script src="${webjarsAt('js/jquery.min.js')}"></script>
```

And don't forget that we must keep `pippo-core` as slim as possible. If any implementation is a little big for core we must move the code in a new module (maybe it's not case of webjars).

**Comment by gitblit** [comment]
Wow.  I'm not sure if we can safely get *that* aggressive with the WebJars handler.  The layout is consistent - but only up-to-a-point - especially when looking at the newer Bower WebJars.

Do you mean to search the classpath for a resource matching that name?  Could get expensive.

@danjee How does Wicket's *current* linking work?  Are they literally depending on `<version>current</version>` or are they interpreting *current* in their WebJar integration?

**Comment by danjee** [comment]
They interpret the `current` word in java code.

**Comment by decebals** [comment]
An idea is to use `WebJarAssetLocator` from `webjars-locator-core`
```
<dependency>
    <groupId>org.webjars</groupId>
    <artifactId>webjars-locator-core</artifactId>
    <version>0.25</version>
</dependency>
```
but again I don't know if it's ok (add some value) to complicate the current (simple) implementation of the  webjars in pippo.

**Comment by gitblit** [comment]
Adding that jar would add quite a few [dependencies]  - Jackson & friends - to core and break one of our design requirements.

I agree that specifying fixed versions in templates is cumbersome.  Maybe we could adopt something like what @danjee is proposing to make it more palatable.

I'm thinking we could try to locate all `pom.properties` that are located within `org/webjars` subdirectories on the classpath.  If we can do that then we can easily create a name-version index to support the proposed `current` version.

Sadly, WebJars do not export a descriptor file in the same location for all jars.  That would have been quite handy.  Instead we'll have to implement some classpath scanning logic without adding a dependency.

[dependencies]: https://github.com/webjars/webjars-locator/blob/master/pom.xml

**Comment by decebals** [comment]
@gitblit I agree. Also, if the implementation is complicated we can abandon this feature.

**Comment by gitblit** [comment]
Assuming no one else has started this, I'll take a stab at this.

**Comment by gitblit** [comment]
I pushed a working implementation of `/current/` support in #180.

**Comment by danjee** [comment]
Thank you! I will update the pippo documentation on webjars.org after the 0.6.0 release.

**Comment by decebals** [comment]
Also will be great to update the documentation on `pippo-site` (branch `release-0.6.0`)
