### ISSUE TITLE
pippo-demo-crud-ng - angularjs webjar has huge size compared to other deps

### ISSUE THREAD

**Issue by balamaci** [decebals/pippo#195]
the .war file produced after pippo-demo-crud-ng  size 6.6MB out of which 3.2MB is angularjs webjar.

**Comment by gitblit** [comment]
Does it matter?  It's a demo for using AngularJS.

**Comment by balamaci** [comment]
Actually the pippo-demo-crud-ng.war (built -P war which removes jetty deps is 5MB) so the webjar is ~60%. Was planning on using it as a base for a blog article about visual testing with a secondary agenda of spreading some awareness about pippo. The angular demo looks good and also has angular hype attached to it, but it also means I cannot really mention pippo as freakishly lightweight.

**Comment by gitblit** [comment]
Pippo *is* light-weight.  Maybe Angular isn't.  Not a Pippo problem, IMO.  You can still proceed with a "thin" Pippo+Angular example using an Angular CDN to avoid the webjar footprint penalty.
