### ISSUE TITLE
Issue in Response.file method

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#204]
The actual code is:
```java
public void file(String filename, InputStream input) {
    checkCommitted();
    finalizeResponse();

    // content type to OCTET_STREAM if it's not set
    if (getContentType() == null) {
        contentType(mimeTypes.getContentType(filename, HttpConstants.ContentType.APPLICATION_OCTET_STREAM));
    }

    if (isHeaderEmpty(HttpConstants.Header.CONTENT_DISPOSITION)) {
        if (filename != null && !filename.isEmpty()) {
            header(HttpConstants.Header.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"");
        } else {
            header(HttpConstants.Header.CONTENT_DISPOSITION, "attachment; filename=\"\"");
        }
    }

    try {
        // by calling httpServletResponse.getOutputStream() we are committing the response
        IoUtils.copy(input, httpServletResponse.getOutputStream());

        // flushing the buffer forces chunked-encoding
        httpServletResponse.flushBuffer();
    } catch (Exception e) {
        throw new PippoRuntimeException(e);
    } finally {
        IoUtils.close(input);
    }
}
```

We push the header map (local variable) to `HttpServletResponse` in `finalizeResponse()` but this method is called early in code so `header(HttpConstants.Header.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"")` do nothing.

My idea was to create a proxy method that are called by each method from `Response` that "commit" the response and in that proxy method to push the local variables to `HttpServletResponse`. We have now  two candidates: `commit` and `finalizeResponse`. I am not so satisfied with actual implementation, are some aspects that are error prone (for example "response already committed"). 
I see now why majority of java web frameworks isolate the "HttpServletResponse" (you have access to a `Response` that it's an holder for variables), the handler returns an object and in servlet/filter is committed the `HttpServletResponse`  by framework; it's easy to implement and safe but in my opinion it's not so powerful.

**Comment by gitblit** [comment]
For the immediate problem you identify we can easily re-order setting the defaults.

```java
 public void file(String filename, InputStream input) {
    checkCommitted();

    // content type to OCTET_STREAM if it's not set
    if (getContentType() == null) {
        contentType(HttpConstants.ContentType.APPLICATION_OCTET_STREAM);
    }

    if (isHeaderEmpty(HttpConstants.Header.CONTENT_DISPOSITION)) {
        if (filename != null && !filename.isEmpty()) {
            header(HttpConstants.Header.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"");
        } else {
            header(HttpConstants.Header.CONTENT_DISPOSITION, "attachment; filename=\"\"");
        }
    }

    // finalize after setting-up defaults
    finalizeResponse();

     try {
            // by calling httpServletResponse.getOutputStream() we are committing the response
            IoUtils.copy(input, httpServletResponse.getOutputStream());

            // flushing the buffer forces chunked-encoding
            httpServletResponse.flushBuffer();
        } catch (Exception e) {
            throw new PippoRuntimeException(e);
        } finally {
            IoUtils.close(input);
        }
}
```

I don't know that we can get away from *response already committed* because of our chain design **unless** we completely extract or hide  the `ServletResponse` from the Pippo Response class.  And by that I really mean we never write anything to the `ServletResponse` from the Pippo `Response`.  The `ServletResponse` would then be finalized/committed by the `RouteDispatcher` after the `RouteMatchChain` has finished execution.
