### ISSUE TITLE
Problem wtih Request.updateEntityFromParameters method

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#206]
In few a sentence: in `Request.updateEntityFromParameters()` pippo doesn't retrieve all fields (plus fields from superclass).

`Customer.java`:
```java
public class Customer extends Entity {
    private String name;
}
```

`Entity.java`:
```java
public class Entity {
    private Long id;
}
```

So, `Request.updateEntityFromParameters(customer)` doesn't 'see' the __id__ field.

**Comment by gitblit** [comment]
:+1: This is a small but *very* useful change. Nice!
