### ISSUE TITLE
Add custom Filters, Extensions in PebbleEngine from Application

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#211]
The idea is that I want to extend Pebble template engine with custom Filters, Extensions.
For example I wish to use an extension built by me for my application. From Pebble {documentation ](http://www.mitchellbosecke.com/pebble/documentation/guide/extending-pebble) I see that it's very simple to do this:
```java
PebbleEngine engine = new PebbleEngine();
engine.addExtension(new MyCustomExtension());
```

but I don't have access to PebbleEngine from Application.

A possible use case could be:
```java
public class MyApplication extends Application {

   @Override
   protected void onInit() {
      PebbleEngine pebbleEngine = ((PebbleTemplateEngine) templateEngine).getPebbleEngine();
      engine.addExtension(new MyCustomExtension());

      // ... add routes
   }

}
```

I have the same problem with all template engines supported by Pippo (Freemarker was tested by me).
I don't know if it's not a good idea to make `TemplateEngine` generic like this:
```java 
public interface TemplateEngine<T> {

    // actual methods
    ...

    // new method
   public <T> get<a_good_name>();
    
}
```

Also I think that we can extend the concept to Servers (Jetty, Undertow) to "catch" the raw server and make some custom configuration (add a filter, or adjust a parameter). Maybe it's nice to have an interface 
```java
public interface X<T> {

    public <T> get<a_good_name>();

}
```

where X must be a nice and clear name.
With this interface I can modify TemplateEngine, WebServer to extends this interface.

What is your opinion?

PS. I have impression that the problem was discussed in other post but I didn't find the post :smile:

**Comment by gitblit** [comment]
Yes. We should do this.  I have an immediate use-case for it - same as you.  I want to add filters or extensions to the Pebble instance.

**Comment by decebals** [comment]
What variant? :smile: 
1. Add a simple `getPebbleEngine()` in PebbleTemplateEngine
2. Add generic to `TemplateEngine` + new method
3. Add interface X and modify `TemplateEngine` and `WebServer` signature

If it's 2. or 3. can you propose a nice name for the interface name and the method name? :smile:

**Comment by gitblit** [comment]
It's gets a little tricky in the rest of the architecture when you start making everything generic.  Remember my proposal for subclassing router and routes and the immense amount of generic sigs in that PR?

I guess I would target 2 for now and see how that goes.

```java
interface TemplateEngine<X> {
   X getEngine();
}

public class PebbleTemplateEngine implements TemplateEngine<PebbleEngine> {
    @Override
    PebbleEngine getEngine() {
        return engine;
    }
}
```

**Comment by gitblit** [comment]
I think we should also pass `Application` to the init method.

```java
void init(Application application, PebbleEngine engine);
```
That would make the setup instructions for [this extension](https://github.com/gitblit/pippo-pebble-emoji) cleaner:

**Comment by decebals** [comment]
Done with this [commit](3a348318f7ed07863f13c12d81c4b4a7c4461ca3).
