### ISSUE TITLE
pippo.ro is not available

### ISSUE THREAD

**Issue by aymer** [decebals/pippo#216]
Hi,

I'm sure you must have noticed pippo.ro is not what it say it is. Anyway to get it back?
B/w, thanks a bunch for this really good framework.

Thanks
Aymer

**Comment by aymer** [comment]
I can see it back up and running. Thanks!

**Comment by decebals** [comment]
Thank you for reporting the problem.
It's a pleasure for me to see that some people consider this web framework valuable.
