### ISSUE TITLE
java8 build fails with javadoc warning

### ISSUE THREAD

**Issue by balamaci** [decebals/pippo#219]
Running 
mvn clean package 
in java8

fails with

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.8:jar (default) on project pippo-core: MavenReportException: Error while
 creating archive:
[ERROR] Exit code: 1 - /home/.../projects/pippo/pippo-core/src/main/java/ro/pippo/core/Application.java:129: warning: no @return
[ERROR] public RuntimeMode getRuntimeMode() {
[ERROR] ^
[ERROR] /home/../projects/pippo/pippo-core/src/main/java/ro/pippo/core/Application.java:164: warning: no description for @param
[ERROR] * @param engineClass
[ERROR] ^
[ERROR] /home/../projects/pippo/pippo-core/src/main/java/ro/pippo/core/Application.java:263: warning: no @return
[ERROR] public Route addPublicResourceRoute() {
[ERROR] ^
[ERROR] /home/../projects/pippo/pippo-core/src/main/java/ro/pippo/core/Application.java:270: warning: no @param for urlPath
[ERROR] public Route addPublicResourceRoute(String urlPath) {
[ERROR] ^

**Comment by balamaci** [comment]
There is a problem with java8 and javadoc plugin.

https://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete

**Comment by decebals** [comment]
On java 7 I received an error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.8:jar (default) on project pippo-core: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - javadoc: error - invalid flag: -Xdoclint:none
```

I must comment my last commit.

**Comment by balamaci** [comment]
I used
<configuration>
         <failOnError>false</failOnError>
</configuration>
and it worked for both java7 and java8.

I think it's better as it works without any additional reading from the user.
