### ISSUE TITLE
Add declarative approach 

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#237]
See https://github.com/gitblit/fathom/issues/8

**Comment by decebals** [comment]
I created a [branch](https://github.com/decebals/pippo/tree/improve_contoller). I have a little issue in DefaultControllerHandler (I don't find a good solution to remove the Guice Injector so the code doesn't pass the compile phase). 
For now I don't have enough time to finish the work so any help is welcome.

**Comment by gitblit** [comment]
I'll try to take a look later this week.

**Comment by decebals** [comment]
Thanks James! It's not an easy task but it's important.

**Comment by danjee** [comment]
This will be interesting

**Comment by decebals** [comment]
I will try to finish work to this feature in next days.

**Comment by decebals** [comment]
I will try to [move forward](https://groups.google.com/forum/#!topic/pippo-java/rclBFE-bc-U) this feature. I hope that this time will be lucky :smile:

**Comment by decebals** [comment]
Done by #341.
