### ISSUE TITLE
Accessing application.properties

### ISSUE THREAD

**Issue by thiagolocatelli** [decebals/pippo#244]
Is there a way to access the application.properties from anywhere within the application? For example, I wanted to use some of the entries I have from a spring boot application to create a DataSource to be used with my repositories. Of course I will have to do it programmatically by getting each property and setup the DataSource, but does the framework provide me a way to get the entries from the property files?

**Comment by decebals** [comment]
Are many possibilities to access `application.properties`.
One possibility is to use `Application.get().getPippoSettings()`. Other possibility is to create `DataSource` in Application.onInit() because in Application you have access at settings.

**Comment by thiagolocatelli** [comment]
That's what I needed, thank you! Gonna try using Dagger 2 with Pippo now!

**Comment by decebals** [comment]
Good. You are welcome.

You can take a look on https://github.com/decebals/pippo/tree/master/pippo-guice, http://www.pippo.ro/mod/guice.html and https://github.com/decebals/pippo-demo/tree/master/pippo-demo-guice.
Also, maybe https://groups.google.com/forum/#!topic/pippo-java/Yr6Q-jM8PNE inspire you to customize Pippo via Dagger 2.

Have fun!
