### ISSUE TITLE
some question about routing

### ISSUE THREAD

**Issue by ScienJus** [decebals/pippo#248]
from a post on google group: [link][1]

**question 1:**

can `{id}` match the empty string?, until now it can, like:

```
router.addRoute(Route.GET("/", emptyRouteHandler));
router.addRoute(Route.GET("/{username}", emptyRouteHandler));

List<RouteMatch> matches = router.findRoutes(HttpConstants.Method.GET, "/");  // matches.size is 2
```

i think it's wrong, `{id}` should be having a default regex like `{id: \w+}`, make sure it will not match an empty string

so i modified `DefaultRouter.VARIABLE_ROUTES_DEFAULT_REGEX` from `([^/]*)` to `([^/]+)`.

**question 2:**

should we add the priority into Route or PatternBinding? maybe just a simple implement like order by PatternBinding.parameterNames.size asc. it will be better than always return the first.

```
// right result
router.addRoute(Route.GET("/login", emptyRouteHandler));
router.addRoute(Route.GET("/{username}", emptyRouteHandler));

// wrong result
router.addRoute(Route.GET("/{username}", emptyRouteHandler));
router.addRoute(Route.GET("/login", emptyRouteHandler));
```

my english is terrible, sorry

[1]: https://groups.google.com/forum/#!topic/pippo-java/7GHaR7JTnuU

**Comment by gitblit** [comment]
> should we add priority into Route or PatternBinding

No. The order of defined routes implies the priority.

**Comment by decebals** [comment]
> i think it's wrong, {id} should be having a default regex like {id: \w+}, make sure it will not match an empty string

I think that is OK to force the path parameter for a route to be not empty. @gitblit what is your opinion?

**Comment by gitblit** [comment]
I'm probably using the existing (short-cut) behavior to avoid registering the same route multiple times with different expressions; changing that may cause me some pain, but that's my problem.

For Pippo, my instinct is requiring a non-empty path parameter value is logical and reasonable.  The proposal by @ScienJus  of `*` to `+` is how I would change it.

**Comment by decebals** [comment]
@ScienJus Can you supply a PR?

**Comment by ScienJus** [comment]
OK, wait a minute, after regex PR,
