### ISSUE TITLE
Visibility of Route.inGroup method

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#251]
I feel that `Route.inGroup` method cannot be public.
I want to prevent something like `Application.GET("myPath", myRouteHandler).inGroup(myGroup)`. I prefer to have a one way to do add route to a group:
```java
RouteGroup myGroup = new RouteGroup();
myGroup.GET("myPath", myRouteHandler");
add(myGroup);
```

One the other hand maybe it's a good idea to collect all routes via `GET, POST, ...`, `addRoute`, `addRouteGroup` in a collection (probably in Router) and to make the "real work" to the end of `Application.init()`. The goal is to prevent the [computation of uriPattern](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/route/Route.java#L127).  Maybe it's only a false issue (only in my mind) and and we do not need to change anything.

**Comment by ScienJus** [comment]
i agree with you, in my idea, we don't need to maintain the relationship  between `RouteGroup` and `Route` after removed `inGroup` method, just concat `group.uriPattern` and `route.uriPattern`, like:

```
//RouteGroup.GET
public RouteGET(String uriPattern, RouteHandler routeHandler) {
    Route route = Route.GET(this.uriPattern.concat(uriPattern), routeHandler);
    routes.add(route);  //routes is a List<Route>
    return route;
}
```

i think it's means that `RouteGroup` more like a helper or a utils to make create route easier
, and i like this way

**Comment by decebals** [comment]
Right now we cannot compute `Route.absoluteUriPattern` in `RouteGroup.addRoute()` and we must do this computation on `Route.getAbsoluteUriPattern()`, method that is triggered by `Route.getAbsoluteUriPattern()`. We need a lazy computation because in my opinion we are too flexible in route group API.

For example with the actual API I can add a route in many ways.

```java
RouteGroup myGroup = new RouteGroup();
myGroup.GET(""myPath", myRouteHandler");
addRouteGroup(myGroup);

// OR

RouteGroup myGroup = new RouteGroup();
GET("myPath", myRouteHandler").inGroup(myGroup);
// addRouteGroup(myGroup); // seems optional in this workflow
```

Also other "not so natural" constructions are allowed:
```java
RouteGroup myGroup = new RouteGroup();
RouteGroup myGroup2 = new RouteGroup();
myGroup2.GET(""myPath", myRouteHandler");
myGroup2.inGroup(myGroup);
addRouteGroup(myGroup2);
```

A possible solution to supply only one workflow for add route group is to supply the parent group in the constructor of the route group (to make parent group a kind of immutable):

```java
RouteGroup myGroup = new RouteGroup();
RouteGroup myGroup2 = new RouteGroup(myGroup);
myGroup2.GET(""myPath", myRouteHandler"); // <-- here I know the 'absoluteUriPattern'
addRouteGroup(myGroup2);

// just in case
addRouteGroup(myGroup) // non sense because I don't have routes on this group
```

It's great that the current implementation of the Route Group is functional and I think that in time we will polish the API :smile:
Maybe I am too perfectionist but it's very important for me to have a simple and clear API

**Comment by ScienJus** [comment]
yes! at first i created `inGroup` method just because this comment

> @ScienJus thanks for your contribution.
This functionality is on our roadmap (https://groups.google.com/forum/#!topic/pippo-java/ocmVEJ7oLw8) but I don't decide how to show the API from this feature in the final form.
My idea is to have a clean and simple API that does not require too much documentation.

> Now in my mind is something similar with:

>RouteGroup usersGroup = RouteGroup("/users");
GET("{id}", routeContext -> { ... }).group(usersGroup);
POST("{id}", routeContext -> { ... }).group(usersGroup);
// add more routes in this group
I will reflect a little bit at this feature.
Any advice is welcome.

now we have the same decision, i will create a PR about removed `inGroup` method and group-route relationship, compute `uriPattern` in `addRoute` method. anything else?

**Comment by decebals** [comment]
Nothing else. Put the `parent` group in constructor of `RouteGroup`. Also we must have a `RouteGroup` without parent parameter (groups on first level without parent, or parent null). Push all logic in Router and not in Application. On `addRouteGroup` we must add group's routes as individual routes in router.
I don't know for moment If we must keep a reference to RouteGroup in Route (`getGroup()`) and in RouteGroup to keep all routes from that group (I think that now we don't need these information but just in case).
