### ISSUE TITLE
Named route group

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#253]
The idea is that we add a new `named` method on `RouteGroup` similar with the same method from `Route`.

Show me the code:

``` java
// create the group with a name
RouteGroup group = new RouteGroup("/users").named("users.");

// add routes for group
group.GET("/", ...).named("getAll");
group.GET("/{id}", ...).named("get");
group.PUT("/{id}", ...).named("update");
group.DELETE("/{id}", ...).named("delete");

// add route group to application
addRouteGroup(group);
```

The idea is that the route name is prefixed automatically with the group name.
Now, you may use the route's name when generating URLs or redirects:

``` java
Map<String, Object> parameters = ...
routeContext.uriFor("users.getAll", parameters);
routeContext.uriFor("users.get", parameters);
routeContext.uriFor("users.update", parameters);
routeContext.uriFor("users.delete", parameters);
// the same for redirect
routeContext.redirect("users.getAll", parameters);
...
```

In my example I used `.` as separator but you can use any character or string.

What you think?

**Comment by gitblit** [comment]
Yeah, I think that is good.

I also think we should consider doing deferred Route addition.

1. Observe the return type of any of [these methods](https://github.com/gitblit/fathom/blob/master/fathom-rest/src/main/java/fathom/rest/RoutesModule.java#L207).
2. Which is [this](https://github.com/gitblit/fathom/blob/master/fathom-rest/src/main/java/fathom/rest/RouteRegistration.java#L37) class.
3. And the asynchronous deferred Route [compilation/addition](https://github.com/gitblit/fathom/blob/master/fathom-rest/src/main/java/fathom/rest/RoutesModule.java#L315
) step.

The basic idea is to allow a route to be configured declaratively before being added to the Router.  You seem to be heading that direction.
