### ISSUE TITLE
Date Param Support

### ISSUE THREAD

**Issue by icirellik** [decebals/pippo#256]
I'm trying to pass a Date in as a parameter to a controller and can't seem to find any examples on how this should work. After some digging through the code I noticed a second annotation `@ParamPattern`, do I need to set a pattern for to make this work?

``` java
public void getHistory(@Param("since") Date since) {
  ...
}
```

**Comment by decebals** [comment]
For now, `@ParamPattern` is used only inside of the entity object (POJO).

For example (it's a pseudocode):
```java
class User {

    @Param
    String name;

    @Param
    @ParamPattern
    Date since;

    // getters and setters

}
```

and now you can use
```java
class MyController extends Controller {

    void createUser(@Form User user) {
        userService.createUser(user);
    }

}
```

We try to improve the controller module with #237 (probably in the next version you will have this improvement). For now I will review the solution proposed by @ScienJus in #257.

**Comment by icirellik** [comment]
This is exactly what I needed, thanks. This works for now.

**Comment by decebals** [comment]
Is it the problem solved? Could you close the issue?
