### ISSUE TITLE
Optional logo display in PippoFilter

### ISSUE THREAD

**Issue by ahfa-noitso** [decebals/pippo#258]
I've started to use Pippo and I really find it a great piece of work.
Just a very tiny enhancement, can we have a system property option that allows showing/hiding the Pippo logo displayed by the PippoFilter in the logs? or give us some control to show/hide it easily instead of having to override the whole init() method. I'm not sure if keeping it hard coded is intended or not, but if it's not then I'm willing to submit a PR if you prefer, thanks.

**Comment by decebals** [comment]
Use `pippo.hideLogo` property (for example ` -Dpippo.hideLogo` from command line).

**Comment by ahfa-noitso** [comment]
Thank you for the answer :)
