### ISSUE TITLE
JettyServer attempts to use keystore password as truststore file path

### ISSUE THREAD

**Issue by JPercivall** [decebals/pippo#265]
On this line it should pass the truststore file path and not the keystore password:

https://github.com/decebals/pippo/blob/93f71655481f3133310019317d90467485f37e1f/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java#L125-L125

**Comment by danjee** [comment]
You are right! Thanks for notice. I will create a PR shortly!

**Comment by decebals** [comment]
It's an issue generated by a copy/paste :smile:

**Comment by JPercivall** [comment]
Looks good, thanks @decebals
