### ISSUE TITLE
customize jackson objectMapper

### ISSUE THREAD

**Issue by amalagaura** [decebals/pippo#274]
I wanted to use JacksonMixInAnnotations to customize the serialization of JSON objects which I cannot control via annotations. It means I need access to the objectMapper instance.

Objectmapper is available via the getObjectMapper method implemented by JacksonJsonEngine.

If I want to override it, do I need to duplicate the JacksonBaseEngine code from pippo-jackson and then add another service initializer? I think I cannot include the pippo-jackson jar because it will cause JacksonJsonEngine to be loaded with the default objectMapper?

Thank you,

**Comment by decebals** [comment]
@gitblit Can you take a look please?

**Comment by gitblit** [comment]
@amalagaura I would...

1. include the `pippo-jackson` dependency
2. subclass `JacksonJsonEngine` and override `getObjectMapper()`
3. call `application.getContentTypeEngines().setContentTypeEngine(new CustomJacksonEngine())`;

**Comment by amalagaura** [comment]
Thank you. That was my first thought as well, but I was concerned it would register multiple contentTypeEngines because of the initializers. 

But I think you are saying that the pippo-jackson would get initialized and register the default but my code would be in my application therefore since setContentTypeEngine writes to a map it would just get overwritten. (sorry, thinking out loud I guess).

thank you

**Comment by ab2971082** [comment]
ok, thanks!
