### ISSUE TITLE
JettyServer.start() blocks due to Jetty server.join()

### ISSUE THREAD

**Issue by sl33nyc** [decebals/pippo#293]
This is related to #273.

Using v0.8, I want to start up some background threads that depend on the web server being fully started, but the call to JettyServer.start() also blocks the main thread from initializing any web server dependencies.  The Spark micro web service framework handles this using a [`CountDownLatch`](https://github.com/perwendel/spark/blob/master/src/main/java/spark/embeddedserver/jetty/EmbeddedJettyServer.java#L129).

In master, I see that the runtime environment will affect whether `server.join()` is called, but then an equivalent, `public` method for `.join()` needs to be implemented across all web server implementations.

**Comment by decebals** [comment]
I have a solution. I will resolve today the issue.

**Comment by decebals** [comment]
Can you help me with a minimum unit test?

**Comment by decebals** [comment]
@sl33nyc, @barrantesgerman Please try the fix. I updated the SNAPSHOT.
I will make some tests to see if I must to do the same thing for Tomcat. I know that Undertow is not affected by this behavior.

**Comment by decebals** [comment]
I tested all servers (jetty, tomcat, undertow and tjws). Everything is OK. I am impressed to see that the tiny TJWS makes a good job :smile:

**Comment by sl33nyc** [comment]
👍

**Comment by barrantesgerman** [comment]
Sorry, this week I've been kind of busy but I'll try the fix

**Comment by barrantesgerman** [comment]
Sorry for taking so long, I've been kind of busy.

I did some tests and I think that all is well.

I would like to share the test is performed if help someone else.

https://github.com/barrantesgerman/pippo-test-server

I discovered two interesting things about Rest Assured

* If you want to test using the session, you must add:
```java
SessionFilter sessionFilter = new SessionFilter();
given().filter(sessionFilter)
```
* If you want to test using any of the pippo-session modules, you should also add:
```java
RestAssured.config = RestAssured.config().sessionConfig(new SessionConfig().sessionIdName("SESSIONID"));
```
To use CookieSessionStrategy

**Comment by decebals** [comment]
@barrantesgerman Thanks
