### ISSUE TITLE
routeMatch.getPathParameters()  always not null

### ISSUE THREAD

**Issue by ab2971082** [decebals/pippo#295]
I found the class DefaultRouteContext's method next() has  a bug!
 
  **Map<String, String> pathParameters = routeMatch.getPathParameters();
            if (pathParameters != null) {**   

pathParameters always not null because in class DefaultRouter : 

 **private Map<String, String> getParameters(PatternBinding binding, String requestUri) {
        if (binding.getParameterNames().isEmpty()) {
            return Collections.EMPTY_MAP;
        }

        Map<String, String> parameters = new HashMap<>();**

**Comment by gitblit** [comment]
The full context is....
```java
Map<String, String> pathParameters = routeMatch.getPathParameters();
if (pathParameters != null) {
    request.setPathParameters(pathParameters);
    log.trace("Added path parameters to request");
}
```

Nothing wrong with setting an empty collection into the `Request` so at worst this is an unnecessary safeguard for the `DefaultRouteContext` but since `RouteContext` is pluggable, other implementations could return `null`.

Not a bug, but thanks for the report.

**Comment by ab2971082** [comment]
I want add parameters extra when use Filters. ex:
 ALL("/v2.*", routeContext -> {
            **String token = routeContext.getHeader("token");
            if (token == null) {
                routeContext.getResponse().json().send(new Result(100, "login fail"));
                return;
            }
            LoginSession loginSession = LocalCache.get(token);
            if (loginSession == null) {
                routeContext.getResponse().json().send(new Result(100, "login fail"));
                return;
            }
          Map<String, String> pathMap = new HashMap<>();
          pathMap.put("userId", loginSession.getUseId()); 
          routeContext.getRequest().setPathParameters(pathMap);**

but setPathParameters fail,  I  found the reason is 

**Map<String, String> pathParameters = routeMatch.getPathParameters();
if (pathParameters != null) {
    request.setPathParameters(pathParameters);
    log.trace("Added path parameters to request");
}**

I rewrite it, @Param("userId") can  get the value.
   
**Map<String, String> pathParameters = routeMatch.getPathParameters();
 if (pathParameters != null && !pathParameters.isEmpty()) {
    request.setPathParameters(pathParameters);
    log.trace("Added path parameters to request");
}**

**Comment by decebals** [comment]
@ab2971082 Your approach is incorrect. In few words, the pathParameters map must be immutable in theory. That map is created by framework from a http request and cannot be modified in application.
The correct approach is to use [Locals concept](http://www.pippo.ro/doc/locals.html) to pass values from a route handler to other route handler.

**Comment by ab2971082** [comment]
ok , thanks!
