### ISSUE TITLE
How can I reset fastjson's SerializerFeature?

### ISSUE THREAD

**Issue by ab2971082** [decebals/pippo#297]
I found  the method toString(Object object) in FastjsonEngine.  
**JSON.toJSONString(object, SerializerFeature.UseISO8601DateFormat);**
How can I use other SerializerFeature ？ For example SerializerFeature.WriteMapNullValue.

**Comment by decebals** [comment]
It's something similar with https://github.com/decebals/pippo/issues/274.

**Comment by decebals** [comment]
Is it the problem  solved? Could you close the issue?
