### ISSUE TITLE
WebJars and UberJars

### ISSUE THREAD

**Issue by ayedo** [decebals/pippo#298]
Hello,

first of all: thanks for your great work on Pippo!

I use the maven-shade plugin to create a single executable jar of my Pippo application. 

When I start the application, the WebjarsResourceHandler looks for jars which have 'META-INF/resources/webjars' folders. In the case of an uber jar, it only finds one such resource, the uber jar itself. It then proceeds to expose every single dependency of my application located in the uber jar as webjar. 

Do you know any fixes for this? How do you distribute stand-alone Pippo applications?

EDIT: Locating the TemplatingEngine using ServiceLocator also does not seem to work. It only works, when I set it manually, using setTemplateEngine in Application.

**Comment by gitblit** [comment]
I haven't tried packaging Pippo with the Shade plugin.  Have you @decebals ?

**Comment by decebals** [comment]
I didn't used the Shade plugin. My approach to run a standalone web application built with Pippo is to create an `app.jar` with a special manifest that contains the main class and the classpath (all dependencies are located in a `lib` folder).
So, the application layout at runtime is:
```
app.jar
lib (maven dependencies)
   undertow.jar
   servlet.jar
   ...
```
To run the application you must execute `java -jar app.jar` from command line.

For more info see [1] and [2].

If you can supply me a quickstart project (preferably on Ghithub)I will take a look.

[1] https://groups.google.com/forum/#!topic/pippo-java/Jtv_3skbozU
[2] https://github.com/decebals/matilda/blob/master/pom.xml#L254

**Comment by ayedo** [comment]
Thanks! Number [1] worked for me.
