### ISSUE TITLE
Encrypted/signed cookie based session

### ISSUE THREAD

**Issue by yan5** [decebals/pippo#299]
Hi 
As discussed over google group, please merge the branch in which you already implemented the encrypted/signed cookie based session to master.
Thanks a lot
Yans

**Comment by decebals** [comment]
Read [Session](http://www.pippo.ro/doc/session.html) section from documentation to find how you can set a custom `SessionManager` for your application.

**Comment by decebals** [comment]
I updated the SNAPSHOT on sonatype

**Comment by yan5** [comment]
That was fast! Thank you,

does this section in the doc still holds true?

> Pippo allow you to customize Session via pippo-session module.
If you want a (custom) session manager in your application then you must inject that manager with:
application.setSesionManager(new SessionManager());

Thanks

**Comment by decebals** [comment]
See [here](https://github.com/decebals/pippo-demo/blob/master/pippo-demo-session/src/main/java/ro/pippo/demo/session/SessionApplication.java#L64) the session demo application.

> does this section in the doc still holds true?

I must do a review of Session section.

**Comment by decebals** [comment]
By the way, Pippo comes with a lot of implementations for Session (ehcache, mongodb, hazelcast, ...). See [here](https://github.com/decebals/pippo/tree/master/pippo-session-parent) the full list. 
Thannks @barrantesgerman.

**Comment by decebals** [comment]
@yan5 Please test the current implementation and if it's OK for you please close it.

**Comment by barrantesgerman** [comment]
Hello @decebals 

Thanks for the constant improvements

I was thinking if everything related to encryption should be in a new implementation of `SessionDataTranscoder`.

Would I like to know your opinion?, and if you agree, I could make the change

**Comment by decebals** [comment]
@barrantesgerman I understand what you say. The idea is not bad. We can use for implementation the wrapper/decorator (pattern) over a regular `SessionDataTranscoder` (it's only an idea).
I don't know if it's so valuable for other session implementation but I think that we can do it, so please propose an implementation.

**Comment by decebals** [comment]
@yan5 We made a little refactoring related to this subject. Please see https://github.com/decebals/pippo/pull/302
