### ISSUE TITLE
Maven dependencies require <type>pom</type> even though they are packaged as jar?

### ISSUE THREAD

**Issue by DanStout** [decebals/pippo#301]
This very similar to an issue as someone else had on the [Google group](https://groups.google.com/forum/#!topic/pippo-java/Jtv_3skbozU), but the provided solution does not work without some additional changes to the pom.xml file, which seem like they should not be required.

After packaging the project as a .zip and extracting it, the pippo-controller jar is stored at `lib/pippo-controller-0.9.0-SNAPSHOT.jar`. The MANIFEST.MF file inside the application's .jar, however, references the path `lib/pippo-controller-0.9.0-20160725.222340-9.jar`, meaning attempting to launch the project fails with the following message:
`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: ro/pippo/controller/ControllerApplication`

Adding `<type>pom</type>` to the pippo-controller dependency in the application's pom.xml seems to fix the issue (the file will have the name given in the MANIFEST.mf) but I'm not sure why this is necessary - the other Pippo subproject jars (guice, pebble, undertow) are correct without having the type specified. The pippo-core dependency, however, also will cause problems without `<type>pom</type>`..

**Comment by decebals** [comment]
I think that It's something related to Maven.
I tested on Pippo demo project, [Matilda](https://github.com/decebals/matilda) and I see that I have the same problem.
My steps:
- `git clone https://github.com/decebals/matilda.git`
- `cd matilda`
-  `mvn clean package`
- `mkdir  dist`
- `unzip target/matilda-0.1.0-SNAPSHOT.zip -d dist`
- `cd dist`
- `java -jar matilda-0.1.0-SNAPSHOT.jar`

The exception stack trace is:
```
Exception in thread "main" java.lang.NoClassDefFoundError: ro/pippo/core/Application
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: ro.pippo.core.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

The problem is that `ls lib | grep pippo-core` returns `pippo-core-0.9.0-SNAPSHOT.jar` but the manifest of the app jar, the `Class-Path` attribute contains `lib/pippo-core-0.9.0-20160725.221621-10.jar`.

 We must investigate this problem in the context of Maven and snapshots. It's not a Pippo issue.

**Comment by decebals** [comment]
See http://stackoverflow.com/questions/10525231/maven-snapshot-jar-file-names-not-consistent-using-maven-assembly-in-manifest-fi

**Comment by DanStout** [comment]
Interesting! I'm surprised Maven has such a bug. Well, this workaround seems to work:

* Add `<outputFileNameMapping>
${artifact.artifactId}-${artifact.baseVersion}${dashClassifier?}.${artifact.extension}
</outputFileNameMapping>` to assembly.xml inside `<dependencySet>` to ensure the .jar files do not have the timestamp in their names
* Add `<useUniqueVersions>false</useUniqueVersions>` to the maven-jar-plugin's `<manifest>` section inside pom.xml to ensure the MANIFEST.mf file uses the correct names

**Comment by decebals** [comment]
Thanks that you share us the solution to this issue.

> Do you think it would be worth adding documentation to pippo.ro containing details about how to setup the assembly plugin in order to create the .zip deployment? It could contain a note that if you are using the snapshot repository then the above workaround will be required.

Will be great and valuable for other developers. 
I like to run my web application as a normal console/desktop application without to worry about the web server, web.xml and other things like these. 
If you have some time please add some words about this subject in [documentation](https://github.com/decebals/pippo-site) .

Are some topics related to how to run an application built with Pippo as a normal application:
- https://groups.google.com/forum/#!topic/pippo-java/Jtv_3skbozU
- https://github.com/decebals/pippo/issues/298
