### ISSUE TITLE
Trimou TEMPLATE_LOCATOR_INVALID_CONFIGURATION running fat jar

### ISSUE THREAD

**Issue by robertoestivill** [decebals/pippo#305]
While developing the [benchmark](https://github.com/decebals/pippo/issues/277) I came across this issue while running a fat jar like 

```
$ java -jar target/my-fat-jar-with-templates.jar 
```

```java
Caused by: org.trimou.exception.MustacheException: TEMPLATE_LOCATOR_INVALID_CONFIGURATION: Invalid root dir: file:/Volumes/rober/workspace/FrameworkBenchmarks/frameworks/Java/pippo-undertow/target/pippo-undertow-0.1.0-SNAPSHOT.jar!/templates
       	at org.trimou.engine.locator.FilePathTemplateLocator.checkRootDir(FilePathTemplateLocator.java:136)
       	at ro.pippo.trimou.PippoTemplateLocator.<init>(PippoTemplateLocator.java:49)
       	at ro.pippo.trimou.TrimouTemplateEngine.init(TrimouTemplateEngine.java:81)
       	at ro.pippo.core.Application.setTemplateEngine(Application.java:178)
       	at ro.pippo.benchmark.PippoApplication.onInit(PippoApplication.java:19)
       	at ro.pippo.core.Application.init(Application.java:98)
       	at ro.pippo.core.route.RouteDispatcher.init(RouteDispatcher.java:70)
       	at ro.pippo.core.PippoFilter.init(PippoFilter.java:95)
       	... 27 more
```

I changed the jar creation maven plugin to use the [official method](http://www.pippo.ro/doc/deployment.html), but the issue still remained. 

I tested the same packaging configuration with a different template engine (pippo-peble) and everything worked fine.

So started digging about what can be wrong with Trimou and I found this:

https://github.com/trimou/trimou/issues/50

Which resulted on this fix 

https://github.com/trimou/trimou/commit/1ab83d622b6cc7ac1269c38394602c5b8d88abe3

I think the issue might be related to fact that  [`PippoTemplateLocator` extends `FilePathTemplateLocator`](https://github.com/decebals/pippo/blob/master/pippo-template-parent/pippo-trimou/src/main/java/ro/pippo/trimou/PippoTemplateLocator.java#L44) instead of `ClassPathTemplateLocator`.

Any thoughts?

**Comment by decebals** [comment]
I will try to take a look. Everything related to Trimou in Pippo is in [TrimouTemplateEngine](https://github.com/decebals/pippo/blob/master/pippo-template-parent/pippo-trimou/src/main/java/ro/pippo/trimou/TrimouTemplateEngine.java) class. 
My idea is to configure somehow the Trimou. I think that the main mechanism to do that is via `init(Application application, MustacheEngineBuilder builder)` method (we do that in [PebbleTemplateEngine](https://github.com/decebals/pippo/blob/master/pippo-template-parent/pippo-pebble/src/main/java/ro/pippo/pebble/PebbleTemplateEngine.java#L101)).

**Comment by decebals** [comment]
Useful links:
https://github.com/decebals/pippo/pull/212#issuecomment-136359578
https://github.com/decebals/pippo-demo/blob/master/pippo-demo-template/src/main/java/ro/pippo/demo/template/PebbleDemo.java#L41

**Comment by decebals** [comment]
In conclusion you can set your `CustomTrimouLocator` in Trimou via `TrimouTemplateEngine. init(Application application, MustacheEngineBuilder builder)`. Also we can modify the actual `PippoTemplateLocator` to extends `ClassPathTemplateLocator` but I don't know the impact for the application that already used Trimou template engine.

**Comment by robertoestivill** [comment]
Thanks for your speedy follow up on this :)
Obviously backward compatibility is important and I wouldn't risk it either.
I guess that It would be nice to have a `TrimouTemplateEngine` that works out of the box without having to do any custom initialization, but I can live with that. 
Thanks again!

**Comment by gitblit** [comment]
I think it was a mistake to use `FileTemplateLocator` and it should be corrected.

**Comment by decebals** [comment]
I committed a possible fix. I tested the modification on [TrimouDemo](https://github.com/decebals/pippo-demo/blob/master/pippo-demo-template/src/main/java/ro/pippo/demo/template/TrimouDemo.java) and everything seems OK.
The modification is minor, I changed our `PippoTemplateLocator` with the builtin `ClassPathTemplateLocator`. 

@robertoestivill Please let me know if the modification resolve your use case

@gitblit I like that Pippo has builtin support for a lot of web servers, template engines, ... I see a problem with the maintenance of these implementations. This issue is a good example. I don't use Trimou, I know nothing about this template engine but I must spent time to fix issues related to this engine. Maybe the core developers must spent time on pippo-core and other fundamental modules and less time on particular implementation. I am scary if someone will find an issue in pippo-session-infinispan or pippo-session-mongodb :smile:

**Comment by gitblit** [comment]
@decebals Where is your sense of adventure?  ;)

So how would you like to proceed?  Do you want to split out modules into an extras repo?

**Comment by decebals** [comment]
@robertoestivill Can we close this issue?

**Comment by robertoestivill** [comment]
@decebals Just tried the fix. No exceptions. Templates are found just fine in fat-jars and IntelliJ is also locating them correctly.
Closing.
