### ISSUE TITLE
Length issues with unicode characters.

### ISSUE THREAD

**Issue by maurits150** [decebals/pippo#306]
Hi,

First thanks for creating this framework.

I'm having issues where sending a string with specials characters seems to have it's length calculated incorrectly.

```java
routeContext.getResponse().text("»»»»»1234567890");
```

The arrow is & raquo;

The client browser receives this:

```
»»»»»12345
```

How can I solve this issue?

I'm on 0.9.0-SNAPSHOT using tomcat. This issue did not happen in version 0.8.0.

**Comment by maurits150** [comment]
I see this line was added during the chunked transfer-encoding commit.

https://github.com/decebals/pippo/commit/bafb890b80dfbe7da8af42f408fbecc2dfdc9a67?diff=split#diff-1139f570296eedff92a5c1cb05865c24R1055

The length calculation could be going wrong here?

**Comment by decebals** [comment]
I will take a look.

**Comment by decebals** [comment]
In few words for string content the method `Response.contentLength(int length)` must contain the bytes length and not the characters length.
For more info see http://stackoverflow.com/questions/2773396/whats-the-content-length-field-in-http-header

**Comment by gitblit** [comment]
Nice catch!

**Comment by decebals** [comment]
By the way, I updated the SNAPSHOT version on Sonatype.

**Comment by maurits150** [comment]
Thanks for the fixes so far. This issue is unfortunately still present when encoding JSON data using pippo-jackson. (tested 1.0.0). When using pippo-gson there are no problems. But I really wish to use jackson.

Code to replicate:

```java
ObjectNode node = new ObjectMapper().createObjectNode();
node.put("test", "»»»»»1234567890");
response.json(node);
````

Output:
```
{"test":"»»»»»1234567
```

**Comment by maurits150** [comment]
Actually when I'm encoding the jackson object using gson (ugly but just for testing) there are also issues.
So I guess it's something higher up in the chain that handles the different encoding types.

Output of jackson object using pippo-gson:
```
{"_children":{"test":{"_value":"»»»»»1234567890"}},"_nodeFactory":{"_cfgBigDecimalExact":fa
```

**Comment by decebals** [comment]
I will take a look but it's not clear for me what you try yo achieve. Show me some code (a [quickstart](http://www.pippo.ro/dev/quickstart.html) project will be perfect).
