### ISSUE TITLE
ParameterValue toList functionality discrepancy

### ISSUE THREAD

**Issue by anantheshadiga** [decebals/pippo#309]
I will have input request parameters like the following

&field=A&field=B&filter=age:[10 TO 20]

I am using `toList` method to get the parameters in a List of String. This works fine if i have same parameter name repeating 'N' number of times, which i do get as List of String. But in case of `filter` parameter in the above example, which has only one parameter, it blindly deletes the `]` character from the parameter value..

This is because of this code https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/ParameterValue.java#L288.

Why is it removing the last `]` character, is there any reason behind it?

**Comment by gitblit** [comment]
It's so you can encode a list as a single parameter.

    MyList=[1,2,3,4,5]

**Comment by anantheshadiga** [comment]
Is it okay to add a getter for the variable `values`(https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/ParameterValue.java#L47),  So that we can call `toList` method only if the `values.length > 1`, else we could use `toString` method.

**Comment by anantheshadiga** [comment]
Thanks @decebals , How do i get the updated code?

**Comment by decebals** [comment]
Build yourself the snapshot version or use the SNAPSHOT version.

[1] http://www.pippo.ro/dev/how-to-build.html
[2] http://www.pippo.ro/dev/maven.html

**Comment by anantheshadiga** [comment]
I have tested with the SNAPSHOT build, this is working as expected. Thanks for the help
