### ISSUE TITLE
(discussion): Correct way of loading resource in Context

### ISSUE THREAD

**Issue by anantheshadiga** [decebals/pippo#313]
I have a resource that needs to get initialized before the server starts up. If the application fails to connect to the resource, I am expecting the server should not start up. What is the right way of loading resource using Pippo framework?

**Comment by gitblit** [comment]
That depends on how you are writing your Pippo app.  For example, if you are using the embedded server you might initialize and inject your resource into `Application` either before `new Pippo()` or `pippo.start()`.

If you are deploying a WAR then you'd have to do it in an `Application` subclass - but you couldn't stop the container from starting.

**Comment by anantheshadiga** [comment]
Is it not better to get the support from Pippo app to initialize the context?

**Comment by gitblit** [comment]
When you say *Context* are you referring to `ro.pippo.core.route.RouteContext` or something else?

**Comment by uknth** [comment]
I believe he is looking for some sort of notification on startup, something like ServletContextListener.

**Comment by decebals** [comment]
First, we must to understand the problem. Maybe a concrete use case will help us to understand what you try to achieve.

**Comment by anantheshadiga** [comment]
I was talking about the [initialContext!](https://tomcat.apache.org/tomcat-7.0-doc/jndi-resources-howto.html), where we can create the resource and initialize the resource object in the JNDI service. As this J2EE standards can we have the support from the Pippo app, where we add series of Resources.

**Comment by decebals** [comment]
You can set the server used by Pippo via `setServer(WebServer server)` method. So, a typical Pippo application start using below code:
```java
new Pippo(new MyApplication()).start();
```  

When you want to come with a particular server you can use something similar with:
```java
new Pippo(new MyApplication()).setServer(new MyServer()).start();
```

where `MyServer extends TomcatServer` for example.
In `MyServer` you can override some methods, in your case `internalStart` or `start`. 
For example:
```
void start() {
     // build myself the tomcat instance (with servlets, filters, ...)
     // check if everything is OK and start tomcat instance
}
``` 

I see now that we can modify `internalStart` to return boolean or other minor refactoring to allow a great customization with minimal custom code.

What you think?

**Comment by decebals** [comment]
@anantheshadiga Did you resolve the problem? With last commits you can add `WebServerInitializer`, `ServletContextListener`. Also the Application instance is injected automatically  in `ServletContext` so you can have access to different parts of application in ServletConext aware component (filter, servlet, listener).
