### ISSUE TITLE
Being fan of Decebal Suiu

### ISSUE THREAD

**Issue by etemelkuran** [decebals/pippo#314]
Is it possible to be a fan of **_Decebal Suiu?_**

**Comment by gitblit** [comment]
I'm a fan but this issue is pointless.  ;)

**Comment by decebals** [comment]
I think that someone else post these crappy messages (the man lost the control of the account).

**Comment by etemelkuran** [comment]
no.

**Comment by decebals** [comment]
:) OK

**Comment by etemelkuran** [comment]
at least you accepted me as a fan.
