### ISSUE TITLE
NullPointerException while fetching `Application.get.getPippoSettings()`

### ISSUE THREAD

**Issue by munendrasn** [decebals/pippo#316]
I have added some constants in `application.properties`,
So, I am trying to fetch these constants using  `Application.get.getPippoSettings()`
Im getting NPE.

I don't if it is good to add the constants to `application.properties`
NPE at this line
```
private static final PippoSettings pippoSettings= Application.get().getPippoSettings();
```

**Comment by decebals** [comment]
`Application.get()` returns not null only in the context of web layer (on a http request). It cannot be useful in a service (server side business layer). For a service you must to inject PippoSettings in that service.
