### ISSUE TITLE
Extend TemplateEngine

### ISSUE THREAD

**Issue by traycho** [decebals/pippo#317]
Hello,

I will be nice to have a possibility of changing template file extension.
For instance with Pebble it is .peb . In case I want to change it to .html there is no direct way.

Probably if you provide a method in the interface Template engine like ,

String fileExtension();

then we could override it for our purpose.

Regards
Traycho

**Comment by decebals** [comment]
Added `setFileExtension(String extension)` in `TemplateEngine`.
You can use `Application.getTemplatateEngine().setFileExtension(myExtension)` or prepare your custom `TemplateEngine` and call `Application.setTemplateEngine(myEngine)`.
