### ISSUE TITLE
Use mock with pippo-test

### ISSUE THREAD

**Issue by ucin** [decebals/pippo#322]
Any idea how can we use mocking with `pippo-test`?
My goal is to mock my business api and dao during frontend test.

Perhaps as following,

```
  @Test
  public void testOnlyWithPassword() {
    PippoRule pippoRule = new PippoRule(new App(new MyTestAbstractModule()));
    given()
      .param("password", "test password")
      .post("/auth")
      .then()
      .statusCode(200)
      .body("status", equalTo("fail"));
  }
```

**Comment by decebals** [comment]
See http://www.pippo.ro/doc/testing.html (unless you've already read)

```java
public class App extends Application {

    protected UserService userService;

    // Override this method in your tests
    protected void createServices() {
        userService = new DatabaseUserService();
//        userService = new InMemoryUserService(); // for test
    }

    @Override
    protected void onInit() {
        createServices();

        // add routes below
    }

}

public class AppTest extends PippoTest {

    @Rule
    public PippoRule pippoRule = new PippoRule(new TestApp());

    @Test
    public void testIndex() {
        when().
            get("/").
        then().
            statusCode(200);
    }

}

public class TestApp extends App {

    protected void createServices() {
        userService = new InMemoryUserService();
    }

}
```

Sure you can use other methods to set the (mock) services in your `App` (setters, builder, factory, DI).

Did you encounter any problem?

**Comment by decebals** [comment]
> but since @Rule applied on class base, I need to create a lot of test class to test different scenario.

I don't understand. You can put many test methods (methods annotated with `Test`) in a class.
If you want to group your test methods in classes you can use a `BaseAppTest` like below:
```java
public abstract class BaseAppTest extends PippoTest {

    @Rule
    public PippoRule pippoRule = new PippoRule(new TestApp());

}

public class TestApp extends App {

    @Override
    protected void createServices() {
        userService = new InMemoryUserService();
    }

}

// Add two concrete test classes

public class Test1 extends BaseAppTest {

    @Test
    public void testIndex() {
        when().
            get("/").
        then().
            statusCode(200);
    }

}

public class Test2 extends BaseAppTest {

    @Test
    public void testSomething() {
         ...
    }

}
```

Did what I said make sense to you?

**Comment by ucin** [comment]
Yes it make sense. What I was considering is the fake implementation for test. In your sample code, is the `InMemoryUserService`. 
Since there are many scenario, I need to create many `InMemoryService` implementation for test.

I'm thinking it will will be more easier if I can use Mockito to mock the `UserService` and implement test scenario in each testing method.

**Comment by ucin** [comment]
Maybe something like this, but for the controller

```
@Test
  public void testValidateEmailAndPasswordWithValidEmailAndPassword_success()
      throws IOException, SQLException, InvalidKeySpecException, NoSuchAlgorithmException {
    String email = "myemail@mail.com";
    String password = "mylong password";

    User user = new User() {
      {
        this.setId(GenerateUUID.getTimeBasedUUID());
        this.setFullname("Wheeler Carson");
        this.setEmail(email);
        this.setPassword(StringHelper.encryptPassword(password));
        this.setIsActive(true);
      }
    };

    Mockito.when(userDAO.getUserByEmail(email)).thenReturn(user);
    User result = authentication.validateEmailAndPassword(email, password);
    assertEquals("failure - result or not equal", user, result);
  }
```

**Comment by decebals** [comment]
I understand what you want to achieve. 

Maybe what you need is a possibility to access your `Application` instance in your test methods and to inject the mock services.

You can inject your mock services via setter method for each service (probably the best implementation is builder fluent - the setter method returns the application)

```java
public class App extends Application {

    private UserService userService; // interface

    public App setUserService(UserService userService) {
        this.userService = userService;

        return this;
    }

    // other methods
}

public class AppTest extends PippoTest {

    @Rule
    public PippoRule pippoRule = new PippoRule(new App());

    public void testABC() {
        UserService userService = Mockito.mock(UserService.class);
        Mockito.when(userService.getUserByEmail(email)).thenReturn(user);
        getApplication().setUserService(userService);

       // test pippo (web) aspects below
    }

}
```

I can add a method `getApplication()` in `PippoRule` or you can save `new App()` (passed as parameter in the constructor of PippoRule) in a class variable to have access to application from test methods.

I will be happy to improve `PippoTest` to meet your requirements (if you see a solution).
In essence `PippoTest` (and `PippoRule`) is a very tiny abstraction. You can build and customize your variant from the scratch. For example someone [1] uses `OkHttp` to test his Pippo application. You have a great freedom with Pippo.

[1] https://github.com/decebals/pippo/issues/277#issuecomment-242866130

**Comment by ucin** [comment]
Yep, that is a workable solution @decebals! Thanks a lot. I'm fine with providing setter method for each service. 
Using `OkHttp` also seem like good solution too.

> You have a great freedom with Pippo.

Indeed, that's why I intend to use it for production application. Awesome project!
