### ISSUE TITLE
Stateless singleton controller to handle requests

### ISSUE THREAD

**Issue by mkhanal** [decebals/pippo#324]
Issue:
Stateful controllers + server states with sessions  = Stateful servers

Details Issue: 
Controller module is very handy as it takes away the boilerplate needed to parse parameters.

Following the layered architecture, if layers(controller/services/...) are singleton and stateless, then layers do not need to be instantiated for every route and thus never need to be garbage collected. This makes app very fast, and at the same time helps push the stateless-ness forward. Since in pippo, unlike rails, the Controllers do not need to be stateful to bind values to its templates, we can just as easily make controllers stateless.

While using controller module
A typical route:
```java
handlerClass = SomeController.class;
GET(path, handlerClass, "methodName");
```
Internally, this keeps the reference of the class and evaluates method so that on every request, the class is re-instantiated and the method is invoked. 

Proposal: 
Accept accept an instance instead of class as : 
```java
handlerInstance= new SomeController();
GET(path, handlerInstance, "methodName");
```
or even
```java
handlerInstance = new SomeController();
GET(path, handlerInstance::methodName)
```
Now this instance can be reused for every call. This also resembles what the application would look like if we do not use the ControllerApplication, and use the ro.pippo.core.Application 's route handling.

**Comment by decebals** [comment]
Thanks for the detail explanation (excellent description of problem).
I don't know yet what approach is better:
- add the instance as singleton (route)
- add the class and the method name (controller)
- add the method reference (controller)
- add a kind of "metadata" - for example class name as string (route and controller)

All the variants have strengths and weaknesses.
For example, if I add the instance or class (use an import java statement in Application with a concrete class name) I'm in trouble when I try to implement the Hot Deployment feature [1]. If I use one `RouteHandler` for all requests (the standard route implementation) someone reports a problem [2] when try to execute requests in parallel. In [3] you will get some details about the current implementation.
In the feature my intention is to use a super declarative approach [4] for pippo-controller, similar with SpringBoot. Definitel we must evolve the `Controller` concept and the whole `pippo-controller` module.

In the meantime I will think to the solution proposed by you. The problem is the backward compatibility. Maybe we find an elegant and simple solution for all cases. 

Thanks again!

[1] https://groups.google.com/d/msg/pippo-java/lTbVWX3ArRs/lrr6XJ9KCQAJ
[2] https://groups.google.com/forum/#!topic/pippo-java/vZaa-0GxU1U
[3] https://github.com/decebals/pippo/issues/263
[4] https://github.com/decebals/pippo/issues/237

**Comment by gitblit** [comment]
@mkhanal Thanks for the suggestion.

Personally, I'm not convinced there is any measurable improvement in forcing controllers to be singletons.  I would also argue that singleton controllers make servers **more stateful** not less; controllers are currently one-time use so it is not possible to preserve or share controller state.

From the perspective of performance and memory consumption...  Yes I suppose it could be demonstrated that memory consumption or performance could be improved by some tiny fraction of less than 1 percent.  But we already instantiate dozens of objects per request cycle (`Request`, `Response`, and `RouteContext` quickly come to mind but there are many others).  I don't think one more will make any measurable difference.

I do agree with your conclusion on sessions.  This is the biggest enemy of a stateless server.  Pippo supports many different session strategies (client-side, server-side in-memory, server-side clustered), thanks to @decebals and @barrantesgerman, I would expect there is one which will suit you.

If we did move forward with singleton controllers, how do you suggest we handle accessing stateful `RouteContext` from singleton controllers?

**Comment by mkhanal** [comment]
@gitblit I'll think aloud here. Let me know what you think (maybe we have a roadmap forum for the framework, that will help me understand where we are headed).

I can see your point that if we can maintain performance and memory footprint even if the controllers are not singleton, then its good enough. 
As long as the optimisation responsibility is not intentionally pushed to the project that is using the framework, pippo should be fine.

When I say stateless system, I would argue that RouteContexts should be **value objects** rather than **states** and the value object can have handlers (callbacks, futures, event listeners) that will allow all necessary routes/middlewares to be handled and propagate the response back. This will allow for more cleaner abstraction. How does work right now if instead of the Controller module we just use the vanilla pippo where route handlers are just plain Labdas ?

**Comment by decebals** [comment]
With #326 (it's just a propose) you can use:
- non-singleton/prototype controllers (actual/default implementation)
- singleton controllers (via new `SingletonControllerFactory`)
- non-singleton & singleton controllers (you can specify optionally in `SingletonControllerFactory` what controller classes are singleton)

Example code for singleton controllers:
```java
public class MyApplication extends ControllerApplication {

        @Override
    protected void onInit() {
        // set singleton controller factory
        setControllerFactory(new SingletonControllerFactory());

        ...
    }

}
```

or directly 
```java
new MyApplication().setControllerFactory(new SingletonControllerFactory())
```

**Comment by decebals** [comment]
@mkhanal Is it OK for you?

**Comment by mkhanal** [comment]
This looks better. 
From the framework roadmap perspective, how do we see things moving forward. 
1. Should the framework take more control over the application like the way spring does. It instantiates beans for us. 
1. Or do we want to let developer have more control, where developer will instantiate and wire the beans/classes, and run custom logic before they are hooked up to the framework.

We are taking the first approach with the change you've made. If that's the case, then the solution you have provided makes sense.

I think we need a roadmap forum. It can be empty for now. We can fill them in with these discussions to bring out a roadmap if needed.

**Comment by ucin** [comment]
@decebals, will this included in next release? I use Pippo mostly for REST service, and always stateless.

**Comment by decebals** [comment]
@ucin If you talk about `SingletonControllerFactory` then yes, the modification is already presented in last release.
If you talk about the possibility to add a controller instance (to have the full control of instantiation) and not the controller class, I don't say NO but we should find an elegant solution, non intrusive one.

Feel free to come with proposes. I am ready to help you with details about the current implementation. It's very important the concept.
In the end, I wish to create something that is useful for many people. This is not a personal project. I am not a dictator :smile: . Anytime I am willing to transfer the project's ownership (for example to Apache Foundation) if the move brings more value/visibility/credibility to project.

**Comment by decebals** [comment]
@mkhanal 
What you say about #350? Is it what you search?

**Comment by ucin** [comment]
Thanks @decebals. Yes I'm talking about `SingletonControllerFactory`. Any example on how to use it?

**Comment by decebals** [comment]
@ucin The `SingletonControllerFactory` class is already present in last release. As example, you can use the snippet code from https://github.com/decebals/pippo/issues/324#issuecomment-258638359. Just set the controller factory to `SingletonControllerFactory`, via `ControllerApplication.setControllerFactory` method. 
The next release comes with a more ambitious approach (see #350), you can pass the controller instance instead of controller class. In this mode you have the full control over the controller instantiations (it's what @mkhanal wants in the end).

**Comment by mkhanal** [comment]
@decebals :1st_place_medal:

**Comment by ucin** [comment]
Hi @decebals, I already following that but still the controller being initiated on every request.

```
 @Override
  protected void onInit() {
    setControllerFactory(new SingletonControllerFactory());
...


    GET("/test/getHelloWorld", TestController.class, "getHelloWorld");
    
```

and the controller


```
package io.comet.streetwise.webapi;

import io.comet.streetwise.dto.ResponseStatus;
import io.comet.streetwise.dto.ResponseSuccess;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ro.pippo.controller.Controller;
import ro.pippo.core.Application;
import ro.pippo.core.Messages;
import ro.pippo.core.route.RouteContext;


import java.sql.Timestamp;
import java.text.SimpleDateFormat;

/**
 * Created by ucin on 11/27/2016.
 */
public class TestController extends Controller {
  private static final Logger log = LoggerFactory.getLogger(TestController.class);
  private static final Messages messages = Application.get().getMessages();
  private static final String appId = Application.get().getPippoSettings().getString("application.id", "0");
  private static final SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss");
  Timestamp timestamp = new Timestamp(System.currentTimeMillis());
  public TestController() {
    System.out.println("test");
  }
  public void getHelloWorld() {
    String resourceId = "674f315825f34ff9b54e79e9afbe295c";
    RouteContext routeContext = getRouteContext();
    String locale = routeContext.getLocal(AppConstant.REQUEST_LANGUAGE);
    String greeting = messages.get("message.hello", locale);

    ResponseSuccess responseSuccess = new ResponseSuccess()
      .setAppId(appId)
      .setResourceId(resourceId)
      .setMessage(greeting)
      .setTimestamp(sdf.format(timestamp))
      .setStatus(ResponseStatus.SUCCESS);
    routeContext.json().send(responseSuccess);
  }
}

```

The constructor part always executed on every request.

**Comment by decebals** [comment]
@ucin 
I cannot reproduce the issue. Can you please try to use with the last **SNAPSHOT** (read [here](http://www.pippo.ro/dev/maven.html) about how to add SNAPSHOT in your pom.xml)?
