### ISSUE TITLE
Handling Accept-Encoding request

### ISSUE THREAD

**Issue by munendrasn** [decebals/pippo#331]
How to handle `Accept-Encoding` header in request?
Suppose `Accept-Encoding=gzip` then, response header should contain `Content-Encoding=gzip`.
How to achieve this?
Just adding header to response wouldn't be sufficient. Is there way already available in `pippo` to handle this or custom implementation is required for this??

**Comment by decebals** [comment]
> Just adding header to response wouldn't be sufficient.

Can you give me more details? Can you supply a code snippet to show me what you try to achieve?

**Comment by decebals** [comment]
You can wrap the response's output stream in a `GzipOutputStream` and write to it.

```java
response.contentType(...);
GzipOutputStream outputStream = new GzipOutputStream(response.getOutputStream());
// write to outputStream
```

For some servlet containers (like Tomcat) you can obtain this feature automatically using configuration (a parameter).

If my code snippet is OK for you, I can add a new method `setGzip` (or something similar) in `Response` class that set automatically the content type and wrap the output stream in a `GzipOutputStream`.

**Comment by munendrasn** [comment]
I think creating a method in `Response` class would be better, so that this can be automatically set

**Comment by decebals** [comment]
Can you confirm that the above snippet resolves your problem?

**Comment by decebals** [comment]
My idea here is to supply an out of the box solution, something that is transparent for end user/developer and that could be implemented via [HttpServletResponseWrapper](http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponseWrapper.html) or by introduction of a new `ResponseWrapper` concept.

**Comment by munendrasn** [comment]
Apologizes for the delayed response. The above snippet solved my problem.
Instead of introducing new `ResponseWrapper`, this can be handled in `Response` class right??
To handle it in `Response` class,  access to `request` is needed.

**Comment by munendrasn** [comment]
I think your idea is introduce `ResponseWrapper` something like in this [link](http://tutorials.jenkov.com/java-servlets/gzip-servlet-filter.html) right?

**Comment by decebals** [comment]
Yes, something like that.

The idea is to inject `GzipOutputStream` directly in `HttpServletRequest` (via `HttpServletRequestWrapper.getOutputStream` method) if the request contains `gzip` in `Accept-Encoding`, to set `gzip` in `Content-Encoding` in HttpServletResponse` and to do nothing Pippo's Response (gzip is transparent). So all responses will be "gzipped" out of the box.

**Comment by munendrasn** [comment]
I think this would be awesome solution

**Comment by decebals** [comment]
I merged the PR that comes with an out of the box support for `gzip`. Also I created a new SNAPSHOT. Please test the modifications using your application and let me know if you encounter any problems.

**Comment by munendrasn** [comment]
@decebals , `gzip` content-encoding is working as expected. But regression has occured due to this. No response is getting committed. With custom errorHandler, it is sending content 2 time

**Comment by munendrasn** [comment]
@decebals, Is there any update on this??
Thank you in advance

**Comment by decebals** [comment]
I will try to test on demo application.

**Comment by decebals** [comment]
I think that now, the code is OK. The idea is that you must finish the `GZipResponseWrapper` (call `finish` method) but the big problem is where to call this method. Initial I tried to finish the response `onPostDispatch` using a `RoutePostDispatchListener` but wasn't OK. After this, I tried to call this function at the end of `RouteDispatcher.onRouteDispatch` method but after some elaborated tests I saw that on error/exception, the template that displays the error is not committed. The third attempt (and I hope that is the last) was to call the method that finish the GZip, at the end of `Response.commit`. Now everything seems to be OK.
@munendrasn Please try the new code. Also, I updated the SNAPSHOT.

**Comment by munendrasn** [comment]
@decebals , I have tested new code..the issue is resolved
