### ISSUE TITLE
Cannot run the MemCached unit tests

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#337]
See https://github.com/decebals/pippo/pull/334#issuecomment-267345437 for details.

**Comment by decebals** [comment]
Probably the fast solution is to comment the MemCached unit tests.

**Comment by munendrasn** [comment]
@decebals, Is it possible to release a minor version like `1.0.1` by commenting the MemCached unit tests?? 
Releasing a minor version would be really helpful for me since i require gzip support and using snapshot in production is not a good idea.

**Comment by decebals** [comment]
@munendrasn Sure, no problem.

**Comment by decebals** [comment]
@munendrasn Version `1.1.0` is available on Maven Central Repository.
