### ISSUE TITLE
Consistency in Parameter Value conversion

### ISSUE THREAD

**Issue by munendrasn** [decebals/pippo#338]
For following url, `example.com?q=&format=json`

while converting q to different data types, response would be as follows
```
routeContext.getParameter("q").toInt() # gives 0(default value)
routeContext.getParameter("q").toString() # gives empty string
routeContext.getParameter("q").toList() # gives a list containing empty string
```
Shouldn't `toList()` return empty list??

This is because in `toList` method in `ParameterValue.java`,  only null check is done.
It would be better to check for this condition also

```
if (isNull() || (values.length==1 && StringUtils.isNullorEmpty(values[0])))
```
This would return `defaultValue` (in this case, empty list).  or is there a reason for present approach??
If my approach looks good, I will raise a PR for this one

**Comment by decebals** [comment]
Probably the correct behavior for your example (`example.com?q=&format=json` and `routeContext.getParameter("q").toList()`) is to return an empty list.

**Comment by munendrasn** [comment]
@decebals I do agree on that.
Even for `toSet()` it should return empty set.
Should I create PR for this one??

**Comment by decebals** [comment]
@munendrasn Please
