### ISSUE TITLE
Feedback/Flash messages

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#34]
Feedback/Flash messages are only available to the next request.

**Comment by gitblit** [comment]
What are your plans for this?

**Comment by decebals** [comment]
I don't know if it's a priority right now. 
I thought little about implementation and what I see now it's to save these type of messages on session and to remove that messages from session on the next request. What I don't like me with this implementation is that it's not stateless but I think that the implementation is clean enough. Maybe it's valuable to add a "stateless" implementation for __Session__ (`ClientSession` or other name - keep state in a cookie similar with play and ninja).
How you see things?

**Comment by gitblit** [comment]
I'm still formulating my opinion on server-side session vs.
session-as-cookie.  I think Session should be an interface so we can choose
different backends.

Storing in *a* session is likely the right place but right now that data
does not automatically go to the template engine.  Response.locals() is
sent to the template engine but that does not include session attributes.

As a start, if a session exists we should probably automatically include
it's attributes in Response.render() OR inject the session itself
put("session", request.getSession()) into the map generated in
Response.render().

**Comment by decebals** [comment]
I created a branch `flash` and I tried to propose an implementation for this feature.
I see some little issues (in implementation) but I think that they are not stoppers.

**Comment by decebals** [comment]
I added some inline comments in the commit https://github.com/decebals/pippo/commit/75734301c8b32997bb7180fc56d2c2ad9ec3979c#comments

**Comment by gitblit** [comment]
This looks good.  Minor improvements...

1. flash.warn(), flash.info(), etc.
2. flash.warn("here is my {} message", "test");

I think a "flash" key convention is great.

**Comment by gitblit** [comment]
Resolved by #90.
