### ISSUE TITLE
Could not locate the default messages resource 'conf/messages.properties'

### ISSUE THREAD

**Issue by 2beers** [decebals/pippo#340]
Hello. I'm new to Pippo. I just checked the errors log and I get this:

```
ERROR ro.pippo.core.Messages  - Could not locate the default messages resource 'conf/messages.properties', please create it.
ERROR ro.pippo.core.Messages  - Could not locate the 'en' messages resource 'conf/messages_en.properties' specified in 'application.languages'.
```

My application.properties files is located in the working directory of my application and has the following content:
```

include = conf/messages.properties, conf/messages_en.properties
application.languages = en
```

I have created both files in conf folder which is also in the working directory of my application.

Am I doing something wrong?

**Comment by decebals** [comment]
The classic layout is [this](https://github.com/decebals/matilda/tree/master/src/main/resources/conf).
The line:
{{{
include = conf/messages.properties, conf/messages_en.properties
}}}
it's a bit strange/uncommon for me.
File `application.properties` is only for settings. Directive `include` allows you to split this file in many much small settings files (put settings for a category/group in separate file). On the other side, `messages` files are only for internationalization (i18n).

For more information please read:
- http://www.pippo.ro/doc/settings.html
- http://www.pippo.ro/doc/internationalization.html

**Comment by 2beers** [comment]
Oh. I understand now.  I removed the `include` line but I'm still getting the error `Could not locate the default messages resource 'conf/messages.properties'`
The file exists in that folder.

**Comment by decebals** [comment]
I think that you can ignore that error, your application should run OK. My impression is that I saw it also on demo some times ago.
Please confirm me that your application runs OK. I will take a look to see why this error message appears.

**Comment by 2beers** [comment]
On this code:
```
		    String lang = routeContext.getParameter("lang").toString();
		    System.out.println("lang: "+ lang);
		    String message;
		    if (lang == null) {
		        message = routeContext.getApplication().getMessages().get("pippo.welcome", routeContext);
		    } else {
		        message = routeContext.getApplication().getMessages().get("pippo.welcome", lang);
		    }
		    System.out.println("Message: "+message);
```

it prints: 
```
lang: null
Message: pippo.welcome
```
I have set `pippo.welcome = Welcome!` in `messages.properties` and `messages_en.properties`
Other than this, the app is working great.

**Comment by decebals** [comment]
The result is OK if your url request doesn't contain a `lang` query parameter (similar with `?lang=RO&...`).
If you want something "out of the box" you should use [RequestLanguageFilter](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/route/RequestLanguageFilter.java). Put this filter in front of your routes like this:
```
// filter all requests and setup the language and locale
GET("/.*", new RequestLanguageFilter(getLanguages(), true, true));
```

I see now that the name `RequestLanguageFilter` is not according our conventional, so the class will be renamed to `LanguageHandler`, but this is another story.

**Comment by 2beers** [comment]
I see your point, but even if language is null this 
`message = routeContext.getApplication().getMessages().get("pippo.welcome", routeContext);`

should return `Welcome!` and not `pippo.welcome` . Or am I missing something?

**Comment by decebals** [comment]
The message key (pippo.welcome) is returned by `Messages.get(String key, RouteContext routeContext)` only if the key does not exist in the messages resource. See [this line of code](https://github.com/decebals/pippo/blob/f143f3172933d35c50265e039323ff8dc3a03dce/pippo-core/src/main/java/ro/pippo/core/Messages.java#L120) for more details.
This means that really Pippo doesn't find your messages files and this is a problem. Do you use Maven? Can you describe the layout or you project?

**Comment by decebals** [comment]
If say in first post that
>  I have created both files in conf folder which is also in the working directory of my application.

Can you double check that you have `conf/messages*.properties` in your out folder (`target/classes` for maven projects)? Maybe your IDE doesn't copy the messages files from `src` to `class` on the compile action.

**Comment by 2beers** [comment]
You're right. I needed to copy `conf` folder to `target/classes`. Now is working. 

If I pack the entire app in an executable  jar, do I need to place `conf` folder in the folder from where I'm running the jar?

Also is there a way to disable `application.languages` from java api, so it doesn't throw an error if I'm not adding the line in `application.properties` file?

**Comment by decebals** [comment]
> If I pack the entire app in an executable jar, do I need to place conf folder in the folder from where I'm running the jar?

If you create an executable jar, you must include `conf` folder (with all files) in that jar.

> Also is there a way to disable application.languages from java api, so it doesn't throw an error if I'm not adding the line in application.properties file?

No. I will think a solution.

Do you want to create an internationalized application or not?

By the way, if you want to use version `1.2.0-SNAPSHOT` you have a new method `RouteContext.getMessage` then can help you to write few code.

**Comment by 2beers** [comment]
Thanks for you answers. 

> If you create an executable jar, you must include conf folder (with all files) in that jar.

Does this mean I can change the config file while the app is running? I'm asking this questions because I want to familiarize with the library. What I can and can't do

**Comment by decebals** [comment]
You cannot change the messages file(s) while the app is running. All the messages are keep in a [cache](https://github.com/decebals/pippo/blob/f143f3172933d35c50265e039323ff8dc3a03dce/pippo-core/src/main/java/ro/pippo/core/Messages.java#L50).

**Comment by decebals** [comment]
Can I close this issue? 
If you need to bypass (disable) the cache in development mode (or to create a flag in `Messages` class that allows you to disable the cache) please create a new issue.
