### ISSUE TITLE
Jade and CSS pre-processor

### ISSUE THREAD

**Issue by Avarel** [decebals/pippo#343]
I'm trying to use the SASS CSS pre-processor with jade templating, however it seems that Pippo does not compile the Sass file into CSS.

The Jade code I tried:
`link(href=pippo.publicAt('sasscss/index.sass'), rel='stylesheet', type="text/css")`
`link(href='sasscss/index.sass', rel='stylesheet', type="text/css")`
`link(href='sasscss/index.css', rel='stylesheet', type="text/css")`

Directories and setup: (Kotlin)
![](https://i.gyazo.com/5a53fe0a851593e9fc96f4ef219d5945.png)

**Comment by decebals** [comment]
Did you read [CSS pre-proecessors](http://www.pippo.ro/mod/css-preprocessors.html) section from documentation?
Did you see the [demo](https://github.com/decebals/pippo-demo/tree/master/pippo-demo-css) application?

**Comment by Avarel** [comment]
Yes, I did. However, it seems my problem is that the Sass compiler does not compile Sass files but only SCSS files (after I translated my CSS to SCSS), is this intended?

**Comment by decebals** [comment]
Internally, _pippo-sasscompiler_ uses [vaadin-sass-compiler](https://github.com/vaadin/sass-compiler). I don't know to much about this library. In Pippo the whole integration is in a simple single class [SassResourceHandler](https://github.com/decebals/pippo/blob/master/pippo-css-parent/pippo-sasscompiler/src/main/java/ro/pippo/sasscompiler/SassResourceHandler.java).

**Comment by Avarel** [comment]
After digging around on the developer console, I found that compiled CSS is not subject to the same treatment as public resources; they are cached while public resources have -ver-xxxxxxx appended to their file names. Is this the intended behavior? (Just asking; since settings in the developers disable the cache)

**Comment by decebals** [comment]
[SassResourceHandler](https://github.com/decebals/pippo/blob/master/pippo-css-parent/pippo-sasscompiler/src/main/java/ro/pippo/sasscompiler/SassResourceHandler.java) is a contribution from @danjee. The implementation is OK from my point of view. In `dev` mode (-Dpippo.mode=dev) it's a good practice to disable the caches from modules (templates, preprocessors, ...).
The demo says that you must add below line in your Application class:
```java
addResourceRoute(new SassResourceHandler("/sasscss", "public/sass"));
```
The resources (*.scss files) are in `resources/public/sass` folder.
The template file should contain a reference to scss `<link rel="stylesheet" type="text/css" href="/sasscss/mixin.scss">`

Probably you have a problem if you use `pippo.publicAt('sasscss/index.sass')` but I am not sure.

Did you encounter a problem?

**Comment by Avarel** [comment]
Alright so accessing directly at `'sasscss/index.sass'` solved the problem. However, I switched to the LESS plugin because it seems to have fewer problems than the SASS one currently. All in all, thanks for your help.
