### ISSUE TITLE
Helper method in Response for setting filename

### ISSUE THREAD

**Issue by vemacs** [decebals/pippo#344]
I'm currently using this code in an application when I need direct access to the response OutputStream (to reduce overhead and avoid blocking Jetty when dynamically generating files, etc...):

    ctx.getResponse().header("Content-Disposition", "attachment; filename=\"" + fileName + "\"");

It would be nice to have a convenience method that takes in fileName as a parameter and sets the header, as my current method feels a bit kludgy.

**Comment by decebals** [comment]
What about [Response(fileName, input)](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Response.java#L952)?

**Comment by vemacs** [comment]
I am currently writing directly to the OutputStream with a ZipOutputStream. I tried implementing this with a PipedInput/OutputStream but it didn't function properly.

**Comment by decebals** [comment]
Pippo works out of the box with GZip on output stream (https://github.com/decebals/pippo/pull/333).

**Comment by decebals** [comment]
Method `Response.file(fileName, input)` uses [IoUtils.copy(input, output)](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/util/IoUtils.java#L45) to copy bytes from input stream to output stream (using a 1024 bytes buffer).

**Comment by vemacs** [comment]
I am not talking about gzipping arbitrary content to the client. I am talking about sending ZIP archives with multiple files using the DEFLATE algorithm to the client without hitting the disk or using unnecessary computation, which neither of those do.On Jan 22, 2017 11:51 AM, Decebal Suiu <notifications@github.com> wrote:Method Response.file(fileName, input) uses IoUtils.copy(input, output) to copy bytes from input stream to output stream (using a 1024 bytes buffer).

**Comment by vemacs** [comment]
<3
