### ISSUE TITLE
New controller and routing system ignores global request interceptors

### ISSUE THREAD

**Issue by dunsunik** [decebals/pippo#345]
1. Whenever I annotate my action method with more then 1 route annotation for example @GET("") and @PUT("") only the first one defined is actualy enabled and executed.

2. I tried to create some basic type of interceptors for example one annotation @JustAtest that is placed on my controller class and a second one annotation @Required that is placed on an action method.
When I annotade my controller class with @JustAtest and some of my action method with @Required only the @Required annotation is executed. Both of them should be executed right ?

3. My application based filters are not executed anymore after using controllers.
In my Application I have defined this filter:

```
// auth user before filter
ALL("/.*", new RouteHandler() {

	@Override
	public void handle(RouteContext routeContext) {
		log.error("WHY IT DOES NOT GET HERE");
	}

});
```

**Comment by dunsunik** [comment]
Bug 3) has been fixed. At least it seems so.

Anyways I think there needs to be a better handling of interceptors.

Whenever I annotate my Controller class with an interceptor and some action method as well both of them should be executed. First should be executed action interceptors, then all class interceptors and base class interceptors.

Thank you

**Comment by decebals** [comment]
> I tried to create some basic type of interceptors for example one annotation @JustAtest that is placed on my controller class and a second one annotation @Required that is placed on an action method.
When I annotade my controller class with @JustAtest and some of my action method with @Required only the @Required annotation is executed. Both of them should be executed right ?

I think that current implementation works well with your scenario. When a controller method is invoked the interceptors on method are executed and AFTER them the interceptors on class are executed.
Your interceptors are not executed because probably you forgot to call `routeContext.next()` method in Interceptor route handler.
Example:
```java
import ro.pippo.controller.Interceptor;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
@Interceptor(LoggingHandler.class)
public @interface Logging {
}
```

```java
import ro.pippo.core.route.RouteContext;
import ro.pippo.core.route.RouteHandler;

public class LoggingHandler implements RouteHandler {

    @Override
    public void handle(RouteContext routeContext) {
        System.out.println("LoggingHandler.handle");
        routeContext.next(); // <<< IMPORTANT
    }

}
```

All interceptors are added in a chain and you can specify in the route handler of the interceptor if you want to call next interceptor or not (according the business logic from interceptor).

**Comment by dunsunik** [comment]
Yes sorry I know I forgot to announce it here :)

Anyways please is it possible to get newly developed route attributes either from a controller's action or filter ?

I can get list of routes using findRoutes or searchRoutes but it gets list of routes. I would like to get a specified 1 route that translated a request to a specified action method.

**Comment by decebals** [comment]
@dunsunik 

I think that #347 resolves your request.

**Comment by decebals** [comment]
> Whenever I annotate my action method with more then 1 route annotation for example @GET("") and @PUT("") only the first one defined is actualy enabled and executed.

For now it's not possible but you have this workaround (use a common method for post and get methods):
```java
class MyController extends Controller {

   @GET
   myGetMethod(...) {
       commonMethod(...);
   }

   @PUT
   myPutMethod(...) {
       commonMethod(...);
   }

   commonMethod(...) {
       // your business
   }

}

**Comment by dunsunik** [comment]
Yes that's how I do it now.

**Comment by dunsunik** [comment]
Hey,

I have tested new method getRoute() that I call in my Authentication interceptor handler.
It returns a route but sadly attributes are no present on a route or better say do not contain my previously set key.
I set an attribute using a transformer (during an application startup). If I print attributes from within that transformer a set attribute is there. But it's not the case when gettting it from my authentication interceptor handler.

Any clue ?
Thank you

**Comment by dunsunik** [comment]
When I print attributes from a controller's action method they there and a previously set key is there as well.
So there seems to be a problem that attributes are not accessible from within interceptor handler.

**Comment by decebals** [comment]
Can you share the code from your transformer (or only the part that create the returned value)?

**Comment by dunsunik** [comment]
```
public class ActivationNotRequiredTransformer implements RouteTransformer {

	@Override
	public Route transform(Route route) {
		Method method = route.getAttribute("__controllerMethod");
		if (method == null) {
			// it's not a controller route; do nothing
			return route;
		}

		if (method.isAnnotationPresent(ActivationNotRequired.class)) {
			System.out.println("not require activation annot");
			// ActivationNotRequired named = method.getAnnotation(ActivationNotRequired.class);
			route.bind("activationNotRequired", true);
		}

		return route;
	}

}

```

**Comment by decebals** [comment]
Thanks. I found a possible bug at [this](https://github.com/decebals/pippo/blob/master/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/ControllerRouteHandler.java#L344) line. When I create the virtual route for interceptor I doesn't pass the attributes from controller route and probably your espectation is to have  these attributes.
Probably it's a better solution to have a single attribute  `__controllerRoute` in interceptor that returns the controller route.

**Comment by dunsunik** [comment]
Well it might be. But still do you think that you need to have to different
routes when practically there just a one ?
I mean logically it would make a sense to return a very same route as you
get from a controller or better route that is filled with same attributes.

**Comment by decebals** [comment]
@dunsunik 
Commit 84ea840 added controller route attributes to interceptor.

**Comment by decebals** [comment]
@dunsunik I don't know if the interceptor is not enough in your case (without the route transformer). For example you can retrieve in interceptor route handler the controller method (via `routeContext.getRoute().getAttribute("__controllerMethod")`) and check if `ActivationNotRequired` annotation is present or not.

**Comment by dunsunik** [comment]
Hey,

No it's ok.
Since your last commit everything seems to be working perfectly !

Thank you
