### ISSUE TITLE
Make the route available in RouteHandler

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#347]
A possibility to retrieve the route metadata (method, uriPattern , attributes, ...) in a `RouteHandler.handle` method.

**Comment by decebals** [comment]
Resolved by commit 5350e79.

**Comment by dunsunik** [comment]
Yes thanks, waiting till it's available on a SNAPSHOT version.

Regards

**Comment by decebals** [comment]
The new SNAPSHOT is available.
