### ISSUE TITLE
Changes to Response ignored in "runAsFinally"-filter on exception

### ISSUE THREAD

**Issue by uldall** [decebals/pippo#349]
I have created the following small test application:
```
public static void main(String... args) {
    Pippo pippo = new Pippo();
    pippo.GET("/hello/", routeContext -> {
    	routeContext.getResponse().ok();
    	throw new RuntimeException("Ouch");
    });
    pippo.ALL("/.*", routeContext -> {
        routeContext.getResponse().header("Cache-Control", "no-cache, no-store, must-revalidate");
	routeContext.getResponse().header("Pragma", "no-cache");
	routeContext.getResponse().header("Expires", "0");
	routeContext.next();
		
	System.out.println("Filter processed.");
    }).runAsFinally();
    pippo.start();
}
```
Which results in the following output when doing a GET on /hello/:
```
2017-02-07T09:07:50.438Z [XNIO-1 task-1] INFO  ro.pippo.core.PippoFilter - Pippo started (PROD)
2017-02-07T09:07:50.452Z [XNIO-1 task-1] ERROR ro.pippo.core.DefaultErrorHandler - Ouch
java.lang.RuntimeException: Ouch
	at com.gamblify.burgundy.content.Main.lambda$0(Main.java:22) ~[classes/:na]
	at ro.pippo.core.route.DefaultRouteContext.handleRoute(DefaultRouteContext.java:352) ~[pippo-core-1.1.0.jar:na]
...
Filter processed.
```

As the output shows the "/.*" filter is correctly called. The changes to the response is however ignored and so the HTTP headers are not added.

**Comment by decebals** [comment]
I understand what you say. Is it important the response state in this case (throw error)?
When a route handler throws an exception (your case), the error handler is called and after this, all finally routes are called. You can see [here](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/route/RouteDispatcher.java#L164) the code. The error handler commits  the response (send a status code or an error page based on a template to the client) and from this perspective, any modification on Request or Response that are made by finally filters/routes ("after filters") are useless.
On "after filters", I do some business/logic operation (release or commit a database connection, ...).

**Comment by uldall** [comment]
What I am trying to achieve is to have a filter which will always add the no-cache HTTP headers. Errors or not. Is there a better way to achieve this?

Is seems a bit illogical that changing the Response sometimes works in the finally filters and sometimes doesn't.

**Comment by gitblit** [comment]
Set the no-cache headers in a filter that runs before your handler rather than trying to set them after your handler.

**Comment by decebals** [comment]
@uldall 
Pippo doesn't reuse the `Request`, `Response`, `RouteContext` instances. On each request from browser/client, Pippo creates new instances for these types. I will try to improve the documentation. 
As @gitblit says, you can achieve your objective using a "before filter" route.  
It's enough to add below route as a "before filter" (a first route that precedes business routes)
```java
ALL("/.*", routeContext -> routeContext.getResponse().noCache()).runAsFinally();
```
