### ISSUE TITLE
Ajax

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#35]
Add support for Ajax requests

**Comment by richdyang** [comment]
I don't understand what you mean. Ajax is more of front-end things. If you'd like the application to response as json, it's ok now. And returning javascript by template is also possible.
Ajax is really the difference in request manner and response message body. For server side, it's nothing to change.

**Comment by decebals** [comment]
Your observation is correct. My idea is to supply a functional minimalist demo (based on jquery ajax). After this step I want to see if I can add something valuable in Pippo to simplify the development of Ajax applications (for example to create a pippo.js). One idea is to brings Pippo named routes to javascript.
It's only an idea with a low priority.

**Comment by decebals** [comment]
I created a basic demo pippo-ajax. The ajax part is implemented using [intercooler.js](http://intercoolerjs.org/) - declarative ajax library.

**Comment by gitblit** [comment]
That's a nifty little library!

**Comment by gitblit** [comment]
I deployed a Bower Webjar for intercooler 0.4.10 so you shouldn't need to use the CDN.

<pre>
Deployed!
It will take a few hours for the Maven Central index to update but you should be
able to start using the Bower WebJar now.

GroupID = org.webjars.bower
ArtifactID = intercooler-js
Version = 0.4.10 
</pre>

**Comment by decebals** [comment]
Nice. I see that it's very easy to write pippo-ajax application using intercoller (simple stuff). If you want, we can improve the pippo-demo-ajax module and add this demo on the master branch (and of course add a simple page `Ajax` on pippo-site).

**Comment by gitblit** [comment]
> add this demo on the master branch

I think that would be a good idea.

**Comment by decebals** [comment]
`<script src="${webjarsAt('intercooler-js/0.4.10/src/intercooler.js')}"></script>` is a little different than a standard `<script src="${webjarsAt('jquery/1.11.1/jquery.min.js')}"></script` (just an example) but it's a solution

**Comment by gitblit** [comment]
I don't get to control the layout of the jar file.  That's part of the autoconversion from Bower to Webjar.

**Comment by decebals** [comment]
Sure. I wrote above comment just to remember the correct syntax :smile:

**Comment by decebals** [comment]
I will try to improve the demo with a CRUD
