### ISSUE TITLE
NotFound (CatchAll) route handler

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#352]
The idea is to have a `RouteHandler` that is called only if no route has been found for a request.
I think that are some good [workarounds](https://groups.google.com/forum/#!topic/pippo-java/1XdtxuULcCk) but probably an improvement in API is welcome.

I propose you to add a new method in `Application` class:
```java
void setNotFoundRouteHandler(RouteHandler routeHandler);
```

What you think, is this idea valuable?

**Comment by gitblit** [comment]
👍 This is a great idea.
