### ISSUE TITLE
Two annotations named Param

### ISSUE THREAD

**Issue by liias** [decebals/pippo#353]
It's too easy to import wrong annotation from ro.pippo.core.Param instead of ro.pippo.controller.extractor.Param (ParamExtractor explicitly checks against the latter).

**Comment by decebals** [comment]
We will find a solution. Thanks for reporting.

**Comment by decebals** [comment]
I propose you to rename `Param` annotation from `ro.pippo.core` to `ParamField`. If you have a better name or a better solution, please let me know.

**Comment by liias** [comment]
No objections as I don't use that annotation from core, so not sure where its used, thus no name preference from me.

**Comment by decebals** [comment]
`Param` annotation from core is used in [Request](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Request.java#L243) when you wish to create/update a POJO object from the current request. I don't know how many people know about this feature and how many people use it.
