### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by lambdaupb** [decebals/pippo#356]
https://github.com/decebals/pippo/blob/f143f3172933d35c50265e039323ff8dc3a03dce/pippo-core/src/main/java/ro/pippo/core/route/ClasspathResourceHandler.java#L37

```
    String resourceName = getResourceBasePath() + "/" + resourcePath;
    return this.getClass().getClassLoader().getResource(resourceName);
```

Missing path normalization leads to a path traversal vulnerability.

I tested it in my own app and was able to retrieve `META-INF/` resource files via a manual GET request with `/.../META-INF/` inserted.

This is really web security 101 and maybe the other handler should be audited for similar vulnerabilities.

**Comment by lambdaupb** [comment]
My apologies, I should have sent this via a private channel so this could be published with a fixed version ready to use.

But it seems impossible to edit the GitHub issue in a way that hides the information needed to abuse it. (https://github.com/isaacs/github/issues/37)
I have changed the title to something boring though.

**Comment by decebals** [comment]
Thanks for reporting the problem! I will investigate the issue as much as possible.

**Comment by decebals** [comment]
Ups, I committed on other branch (reloading) but now it's OK because I merged that branch on master. It's tricky when you work on multiple branches/features :smile:
