### ISSUE TITLE
Can pippo work with spring boot ?

### ISSUE THREAD

**Issue by paolog22** [decebals/pippo#358]
thank you for this project.. i just want to know if pippo with work parallel with spring boot .
thanks

**Comment by decebals** [comment]
It is not clear for me what means "work parallel".
Can you elaborate a little bit on this topic?

**Comment by paolog22** [comment]
@decebals sorry sir.. my question is .. can i use pippo withing spring boot. because i have a current project build with spring boot and i want to use some features of pippo . 
thanks :)

**Comment by decebals** [comment]
@paolog22
Spring Boot = Spring + Auto (Magic) Configuration via annotation
I think that it's possible with a little bit code.
Pippo comes with a good/nice support for Spring (see [doc](http://www.pippo.ro/mod/spring.html)). 
If you want an out of the box support, then you should write a Spring Boot starter for Pippo. I think that it's not a difficult task.
If you want something lite (you don't want to implement a full Spring Boot starter) below I present you some guidelines:
- inject your Pippo's Application class
```java
@Component
@EnableAutoConfiguration
@ComponentScan
public class MyApplication extends Application {

    @Autowired
    private MyService myService;

    @Autowired
    private ApplicationContext applicationContext;

    /**
     * Spring boot main method
     */
    public static void main(String[] args) {
        SpringApplication.run(MyApplication.class, args);
    }

    @Override
    protected void onInit() {
        // registering SpringControllerFactory
        setControllerFactory(new SpringControllerFactory(applicationContext));

        // add controllers
        addControllers(MyController.class); // one instance for EACH request
        // or
        addControllers(/*new ContactsController()*/ contactsController); // one instance for ALL requests (contactsController is declared in Spring and it's injected by Spring in application)
    }

}
```
- add `WicketFilter`
```java
@Configuration
public class PippoInitializer implements ServletContextInitializer {

    private static final String APPLICATION_BEAN_PARAM = "applicationBean";

    @Override
    public void onStartup(ServletContext sc) throws ServletException {
        FilterRegistration filter = sc.addFilter("pippoFilter",
                PIppoFilter.class);
        filter.setInitParameter(PippoFilter.APPLICATION_FACTORY_PARAM,
                SpringWebApplicationFactory.class.getName());
        filter.setInitParameter(APPLICATION_BEAN_PARAM, "myApplication");
//        filter.setInitParameter(PippoFilter.FILTER_MAPPING_PARAM, "/*");
//        filter.addMappingForUrlPatterns(null, false, "/*");
    }

}
```

**Comment by paolog22** [comment]
@decebals thank you sir

**Comment by decebals** [comment]
Please let me know if you did it.

**Comment by decebals** [comment]
Can I close this issue? Did you find a solution?

**Comment by paolog22** [comment]
@decebals  yes please. thanks awesome.. love you man :D
