### ISSUE TITLE
routeContext redirect in the same RouteGroup

### ISSUE THREAD

**Issue by 2beers** [decebals/pippo#365]
I have this location: `localhost/v1/me` 
Basically in` V1Routes extends RouteGroup` I have `addRouteGroup(new MeRoutes());`

In `MeRoutes` I want to redirect a location `localhost/v1/me` to `localhost/v1/me/something` 
Here is my code:

```
//this will redirect to localhost/something
GET("/", routeContext -> routeContext.redirect("something"); );
```

is not working it redirects to `localhost/something`

I have to do something like this

`GET("/", routeContext -> routeContext.redirect("v1/me/something"); );`

to make it work. 

Is there a way to avoid writing the full path when redirecting ?

**Comment by decebals** [comment]
For the moment I don't see a possibility to avoid writing the full path when redirecting. The `Route` class contains `absoluteUriPattern` field (it's not visible outside) that contains the full `uriPattern` (including the route group path) but I don't know if it can help us. 
If you see a modality/idea to avoid writing the full path when redirecting, please let me know.

**Comment by 2beers** [comment]
I think an OK solution will be to have access to current route path

`routeContext -> routeContext.redirect(routeContext.getPath() + "something");`

or

```
public MeRoutes() {
	super("/me");
	String path = this.getPath();
        routeContext -> routeContext.redirect(path + "something");
```

**Comment by decebals** [comment]
I think that you can use `redirect(String nameOrUriPattern, Map<String, Object> parameters)`  from` routeContext` (give a nice name to the referenced route ).

```java
GET("/something", ...).named("something");
routeContext.redirect("something" /* the route name*/, parameters);
```

You can retrieve the current Route via routeContext with `getRoute()` (maybe it's useful for you in some cases).

**Comment by 2beers** [comment]
Thanks. That seems to work somehow, but I think you have a bug.

If I use
`pippo.getServer().setPippoFilterPath("/api/*");`

I will redirect to this url
`http://localhost:8081/api/api/v1/me/something`  

`api/api` is wrong there

**Comment by decebals** [comment]
@2beers Can you close this issue and create a new one with the content of your last comment?
