### ISSUE TITLE
Redirecting to named routes using setPippoFilterPath settings

### ISSUE THREAD

**Issue by 2beers** [decebals/pippo#367]
If I use
`pippo.getServer().setPippoFilterPath("/api/*");`

and try to redirect to a named route
```
GET("/something", ...).named("something");
routeContext.redirect("something" /* the route name*/, parameters);
```

It will redirect to an url by appending the _filter path_ to the path that already has _filter path_ included
`http://localhost:8081/api/api/v1/me/something`  

`api/api` is wrong there

**Comment by liias** [comment]
This fix broke publicAt() extension for me if using custom root path for the application, like
pippo.setFilterPath("/stats/*")

**Comment by decebals** [comment]
@liias
I will take a look. It's time to add more unit tests.
