### ISSUE TITLE
JettyRule with JettyServer hangs when multiple tests present

### ISSUE THREAD

**Issue by lorrin** [decebals/pippo#371]
I'm having trouble running more than one test method in a single JUnit test class. Sample code below.

`test1` passes, `test2` (which is identical) hangs at `startLatch.await();` in JettyServer (https://github.com/decebals/pippo/blob/release-1.4.0/pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java#L75)

```
package jettytest.hang;

import org.junit.Rule;
import org.junit.Test;
import ro.pippo.core.Application;
import ro.pippo.core.HttpConstants.StatusCode;
import ro.pippo.test.PippoRule;
import ro.pippo.test.PippoTest;

public class JettyTest extends PippoTest {
    private final static class MyApplication extends Application {
        @Override
        protected void onInit() {
            GET("/", routeContext -> routeContext.status(200));
        }
    };

    @Rule
    public PippoRule pippoRule = new PippoRule(new MyApplication());

    @Test
    public void test1() {
        when().
                get("/").
                then().
                statusCode(StatusCode.OK);
        ;
    }

    @Test
    public void test2() {
        when().
                get("/").
                then().
                statusCode(StatusCode.OK);
        ;
    }
}
```

**Comment by decebals** [comment]
@lorrin Thanks for reporting! 
It seems that is https://github.com/decebals/pippo/issues/273. I will take a look.

**Comment by decebals** [comment]
@lorrin I cannot reproduce the issue.

![image](https://user-images.githubusercontent.com/1248311/27729320-2014577c-5d8e-11e7-9a87-683ff50f70d4.png)

Can you supply more information please?

**Comment by lorrin** [comment]
@decebals , thanks for the quick follow-up! I've double-checked and I can reproduce inside both IntelliJ and the Maven command line.

Here's the `pom.xml` I'm using:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>jettytest.hang</groupId>
    <artifactId>pippo-371</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <pippo.version>1.4.0</pippo.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>ro.pippo</groupId>
            <artifactId>pippo-core</artifactId>
            <version>${pippo.version}</version>
        </dependency>

        <dependency>
            <groupId>ro.pippo</groupId>
            <artifactId>pippo-jetty</artifactId>
            <version>${pippo.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.21</version>
        </dependency>

        <dependency>
            <groupId>ro.pippo</groupId>
            <artifactId>pippo-test</artifactId>
            <version>${pippo.version}</version>
        </dependency>
    </dependencies>
</project
```

```
$ mvn -version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T12:39:06-07:00)
Maven home: /opt/local/share/java/maven3
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```
`mvn test -Dtest="JettyTest#test1` and `mvn test -Dtest="JettyTest#test2` both succeed, `mvn test` hangs, just like when I run in IntelliJ.

**Comment by decebals** [comment]
I created https://github.com/decebals/pippo-371 project to have both the same base code.
The code runs OK on my machine (Ubuntu 16.04) from Idea IntelliJ(2017.1.4) and from command line:

![image](https://user-images.githubusercontent.com/1248311/27758516-5b900e00-5e1e-11e7-8a7d-468f52308d5d.png)

![image](https://user-images.githubusercontent.com/1248311/27758525-9c98babe-5e1e-11e7-8cf9-5c1fbc079a2b.png)

Can you clone the test project from Github (https://github.com/decebals/pippo-371) and run the tests?

**Comment by lorrin** [comment]
Very interesting! So I pulled your code and it behaves the same as mine. So it must be some machine-specific issue. FWIW, the hang on the command line looks like this:
```
$ mvn test -Dtest="JettyTest#test2"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building pippo-371 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pippo-371 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/lorrin.nelson/Code/pippo-371/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ pippo-371 ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ pippo-371 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/lorrin.nelson/Code/pippo-371/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ pippo-371 ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ pippo-371 ---
[INFO] Surefire report directory: /Users/lorrin.nelson/Code/pippo-371/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running JettyTest
log4j:WARN No appenders could be found for logger (ro.pippo.core.util.ClasspathUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

I'll try to provide some more info on where the hang is from the IntelliJ debugger.

**Comment by lorrin** [comment]
OK, I traced it:

First test, PippoRule.startPippo -> Pippo.start -> JettyServer.start, calls `startLatch.await()`. At time of call, count is 1. start had submitted `executor.submit(this::internalStart);`, that then runs server.start, startLatch.countDown(), server.join. Unblocks main thread.

Second test, when PippoRule constructor calls pippo.getServer, `server` is null, finds it via ServiceLocator. This is a different JettyServer instance with a different startLatch instance whose value is 1.

PippoRule.startPippo -> Pippo.start -> JettyServer.start, calls `startLatch.await()`. At time of call, count is 1. start had submitted `executor.submit(this::internalStart);`, that then runs server.start, which throws java.net.BindException: Address already in use, so startLatch.countDown() is never called. main thread never unblocked.

Not sure if the problem is that shouldn't be getting a new JettyServer or that the new JettyServer should be getting a new port or that the old one is still bound to the port. Related to https://github.com/decebals/pippo/blob/master/pippo-test/src/main/java/ro/pippo/test/PippoRule.java#L93 being commented out?

**Comment by decebals** [comment]
I uncommented the line https://github.com/decebals/pippo/blob/master/pippo-test/src/main/java/ro/pippo/test/PippoRule.java#L93. The bug in pippo-core was fixed  when I implemented support for Hot Reloading.

I moved the test projiect to Pippo `1.5.0-SNAPSHOT`(to include the above modification). I added support for Travis CI in https://github.com/decebals/pippo-371. I see that build passing and the tests are OK (https://travis-ci.org/decebals/pippo-371).

Please pull the project and run the tests.

**Comment by decebals** [comment]
I revert the test project to Pippo 1.4.0 and the result from Travis CI is "build passing". I cannot reproduce the problem.

**Comment by decebals** [comment]
In the end, I reactivated a simple workaround in a new [issue-371] (https://github.com/decebals/pippo/tree/issue-371) branch. It's a solution proposed in https://github.com/decebals/pippo/issues/273.

@lorrin If you have some free time, please check this solution:
```
git clone https://github.com/decebals/pippo.git
cd pippo
git branch issue-371
mvn clean install 
```

Then, go to test project and change `pippo.version` to 1.5.0-SNAPSHOT.

**Comment by lorrin** [comment]
That solves the problem! Was calling `server.join()` preventing the shutdown lifecycle from executing between tests?

**Comment by decebals** [comment]
Great news. 

> Was calling server.join() preventing the shutdown lifecycle from executing between tests?

Yes. For more information see https://github.com/decebals/pippo/issues/273#issuecomment-220683262.
I don't understand why on my machine or on Travic CI I cannot replicate the issue. Why other people that use Pippo don't have this problem?

I will merge the branch that resolves the problem.

**Comment by decebals** [comment]
I created a new SNAPSHOT. Please use it until a new release.

**Comment by decebals** [comment]
Is it OK to close this issue?

**Comment by lorrin** [comment]
Yes, thanks!
