### ISSUE TITLE
HTTP PATCH 

### ISSUE THREAD

**Issue by 2beers** [decebals/pippo#374]
Maybe not that important but you should add HTTP PATCH as well

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH

**Comment by decebals** [comment]
https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/route/Route.java#L125 ?

**Comment by decebals** [comment]
I see that `PATCH` method exists in `Routing` (and `Application` because implements `Routing`).

**Comment by 2beers** [comment]
oh.. yes Not sure why I couldn't find it. But if we're still here so I don't have to open another thread you should add `CONNECT` method as well : https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT

**Comment by decebals** [comment]
Do you use all these methods or you want to have the complete collection? :smile:

**Comment by 2beers** [comment]
PATCH method yes, CONNECT not so much, but I though is a good add. Who knows when someone might need it, plus you just need to add 3 -4 lines of code

**Comment by decebals** [comment]
Resolved by 2871d032645bc255e0177d9a00ed8f42de6eeb42.
