### ISSUE TITLE
Jetty startup issues are silently dropped

### ISSUE THREAD

**Issue by lorrin** [decebals/pippo#375]
When Jetty fails to start, the exception is caught and wrapped in a PippoRuntimeException (https://github.com/decebals/pippo/blob/master/pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java#L126) but then this exception silently vanishes inside the Executor that invoked `internalStart`. https://github.com/decebals/pippo/blob/master/pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java#L75 waits forever for `internalStart` to succeed.

I'm a bit confused by the purpose of the Executor here. If `start` is going to block until the executor completes, why doesn't it just do the startup logic on its own thread?

As a work-around, I've added some logging when this happens.
```
$ git diff
diff --git a/pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java b/pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java
index cd96706d..753d307e 100644
--- a/pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java
+++ b/pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java
@@ -123,6 +123,7 @@ public class JettyServer extends AbstractWebServer<JettySettings> {
                 server.join();
             }
         } catch (Exception e) {
+            log.error("Unable to launch Jetty", e);
             throw new PippoRuntimeException(e);
         }
     }
```

Common examples are port already in use, keystore configuration issues.

**Comment by decebals** [comment]
Very good observation. In last period I have been trying to improve readability for `*Server` classes.
If you take a look to the [history](https://github.com/decebals/pippo/commits/master/pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java) of `JettyServer` you will see that the executor appears when I resolved https://github.com/decebals/pippo/issues/293.
The idea is that the line [server.join()](https://github.com/decebals/pippo/blob/master/pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java#L123) block the thread, and this action is not good if you want to run some code after Jetty/Pippo start (see https://github.com/decebals/pippo/issues/293, https://github.com/decebals/pippo/issues/273 and https://github.com/decebals/pippo/issues/371).
For the issues related to PippoTest, the solution with call `server.join` only in non `test` mode is simple and clean (an it's recommended bu people from Jetty).
Maybe from https://github.com/decebals/pippo/issues/293 the correct solution/approach is to move the code with executor outside, in the main class that create and start Pippo.
If you have some idea please let me know.

**Comment by lorrin** [comment]
Thanks for the quick response! I'm still coming up to speed here, but I'm wondering if this has gotten more complicated than it needs to be. Why is server.join being called at all? That just is causing an executor thread with no additional work to waits for Jetty to exit AFAICT. It sounds like that came into play regarding the intent to support two competing needs: to know when the server has started (which is achieved with waiting for server.start to return) and to not block while waiting for the server to come up.

What if the Pippo start method returned a CompletableFuture that did all the setup, invoked `start`, but not `join`, and then returned the Jetty server class? That would support fire-and-forget, but you could also `get` the future to observe exceptions and use the returned server's `join` to build shutdown hooks.

**Comment by decebals** [comment]
The main issue is related to run unit tests via `PippoTest` class. A detailed information about the role of `server.join()` method is presented in https://github.com/decebals/pippo/issues/273#issuecomment-220683262.

> but I'm wondering if this has gotten more complicated than it needs to be.

I feel the same. The executor code is only to not block the main thread and is a little bit complicated to read and explain.
Probably @sl33nyc the reporter of https://github.com/decebals/pippo/issues/293 wants to do something like:
```java
public static void main(String[] args) {
    Pippo pippo = new Pippo(new MyApplication());
    pippo.start(); // <- this call block the main thread
   // put here additional code (for example use a WebClient and call a rest service created via Pippo)
}
```

The classic code is:
```java
public static void main(String[] args) {
    Pippo pippo = new Pippo(new MyApplication());
    pippo.start(); // <- this call block the main thread
}
```
If we don't call `server.join()` method in `pippo.start()` method then the program ends quickly and you cannot post requests to server via the internet browser.

The use case reported in https://github.com/decebals/pippo/issues/293 is very rare in practice and probably the correct approach is to let the user to treat themselves in his code and to remove the executor from JettyServer/TomcatServer.

> What if the Pippo start method returned a CompletableFuture that did all the setup, invoked start, but not join, and then returned the Jetty server class? That would support fire-and-forget, but you could also get the future to observe exceptions and use the returned server's join to build shutdown hooks.

Can you post some snippet/pseudo code?

**Comment by lorrin** [comment]
In my testing, `server.join` is not required to keep the server alive when running Pippo stand-alone. https://stackoverflow.com/questions/15924874/embedded-jetty-why-to-use-join#comment59368803_15925026 says this is because the server threadpool contains non-daemon threads.

**Comment by lorrin** [comment]
A subtlety is that `start()` takes a little while to run, and it doesn't start the non-daemon threads immediately. So if you call `start()` async and then your main thread exits before those non-daemon threads have started up, then the JVM quits.

**Comment by lorrin** [comment]
I have tried just putting everything inside JettyServer's `start()` method. No latch, no executor service, no `join`. This seems to work as desired. 
`pippo.start()` will return once the server is up. At this point, Jetty has started non-daemon threads. If the main thread does nothing else (exits), then Jetty and the JVM will stay up. If the main thread wants to do additional work (like #293), it can. (I think the reason this wasn't possible before was that pippo.start was calling `join`.) Tests work; no issues like #371. If startup fails, exceptions bubble up to main and are easily observed.

**Comment by decebals** [comment]
Thanks for investigation! Do you wish to submit a PR?
