### ISSUE TITLE
NullPointerException when rendering a SASS file stored inside jar

### ISSUE THREAD

**Issue by SR-G** [decebals/pippo#379]
I'm using PIPPO 1.4.0 with SASS handler activated.
Everything works fine under eclipse (with css ressources available on disk. I have a `public/sass/main.scss` file, correctly published at runtime from eclipse under the web path `/css/main.scss` by the handler).

Handler activated through:
```
final String contextSassPath = "/css";
addResourceRoute(new SassResourceHandler(contextSassPath, "public/sass"));
```

Sadly, when executing PIPPO on a remote server with everything embedded in the jar, it does not work anymore (whereas .mustache templates are now correctly working).

```
Caused by: ro.pippo.core.PippoRuntimeException: java.lang.NullPointerException
	at ro.pippo.sasscompiler.SassResourceHandler.sendResource(SassResourceHandler.java:73) ~[pippo-sasscompiler-1.4.0.jar:?]
	at ro.pippo.core.route.UrlResourceHandler.streamResource(UrlResourceHandler.java:122) ~[pippo-core-1.4.0.jar:?]
	... 33 more
```

and error : 
```
18:38:52.068 [qtp19734599-36] ERROR ro.pippo.core.DefaultErrorHandler - Failed to stream resource jar:file:/mypath/myjar-1.0.0-SNAPSHOT.jar!/public/sass/main.scss
```

The `/public/sass/main.scss` is available inside the jar.

I think it was working in PIPPO 0.9.

**Comment by decebals** [comment]
I will take a look,

**Comment by decebals** [comment]
Any improvement/resolution? Can I close this issue?

**Comment by SR-G** [comment]
Just for the heads-up (long time after initial post) : 

- problem is the same whatever the pippo version is (1.12.0, 1.4.0, or even 0.9.0 (i was wrong when saying it was probably working at that time))

- in the end, the problem is in the vaadin class ScssStyleSheet.java, which is just relying on a new File(identifier) (leading to a "null" object in my situation), whereas it should be more clever (> if file is not found on filesystem, it should then just use a getResourceAsStream() in order to extract it from the classpath)

- i work'arounded the problem by keeping these resources outside the jar (which is way less elegant, but working out of the box)

**Comment by decebals** [comment]
@SR-G Thanks that you share with us this information. I am curios if SASS Vaadin library is maintained yet.
