### ISSUE TITLE
Limit maximum request body size

### ISSUE THREAD

**Issue by lambdaupb** [decebals/pippo#380]
There is a setting on `Application` limiting the size of an upload, but that does not seem to be limiting the size of request bodies like JSON.

It is pretty easy to send 1GiB of gzip content-encoded garbage and make the server throw an OutOfMemoryError.

This should probably be handled in `Request.getBody()`. Thinking about it, it should really be implemented in the server, since it could easily be 1GiB of HTTP headers as well.

`UndertowOptions` has `MAX_ENTITY_SIZE` which is unlimited by default.

**Comment by lambdaupb** [comment]
So, if anyone needs to get it working *__now__*, here is a dirty hack:

```
    this.pippo.start();
    try {
      UndertowServer undertowServer = (UndertowServer) pippo.getServer();
      Field f = undertowServer.getClass().getDeclaredField("server");
      f.setAccessible(true);
      Undertow undertow = (Undertow) f.get(undertowServer);
      Field serverOptionsField = undertow.getClass().getDeclaredField("serverOptions");
      serverOptionsField.setAccessible(true);
      OptionMap serverOptions = (OptionMap) serverOptionsField.get(undertow);
      Field mapField = serverOptions.getClass().getDeclaredField("value");
      mapField.setAccessible(true);
      Map<Option<?>, Object> map = (Map<Option<?>, Object>) mapField.get(serverOptions);

      HashMap<Option<?>, Object> hashMap = new HashMap<>();
      hashMap.putAll( map);

      hashMap.put(UndertowOptions.MAX_ENTITY_SIZE, Long.valueOf(5*1024*1024));
      mapField.set(serverOptions, hashMap);
    } catch (NoSuchFieldException e) {
      e.printStackTrace();
    } catch (IllegalAccessException e) {
      e.printStackTrace();
    }
    pippo.stop();
    pippo.start();
```

**Comment by decebals** [comment]
The clean solution is to set a custom server instance in Pippo. See [doc](http://www.pippo.ro/doc/server.html) for more information. In your case you should extends `UndertowServer.createServer` method.

I think that a possible improvement is to expose `Undertow.Builder` (`onUndertowBuild(Undertow.Builder builder)` or a better name) before [return[(https://github.com/decebals/pippo/blob/master/pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/UndertowServer.java#L152) from `UndertowServer.createServer` method. On `Undertow.Builder` you can set options.

Other nice solution is to specify the undertow options in `application.properties` but I don't know the sattus of https://github.com/decebals/pippo/issues/359. Maybe @munendrasn  can tell us how he resolved the issue.

**Comment by decebals** [comment]
#359 is resolved. You should set `undertow.server.MAX_ENTITY_SIZE` property in you `application.properties` file.
