### ISSUE TITLE
It's not a issue, Just to all you know

### ISSUE THREAD

**Issue by MateusGabi** [decebals/pippo#390]
I'm developing a shell-script or something like that creates an easy Pippo application. It will work like `laravel new [[app-name]]` ou `ng new [[app-name]]`

A "clonable" app will be avaible here [https://github.com/MateusGabi/My-Pippo-Quickstart](https://github.com/MateusGabi/My-Pippo-Quickstart)

(my english is not good),
Thank you!

**Comment by decebals** [comment]
What you say about http://www.pippo.ro/dev/quickstart.html?

**Comment by MateusGabi** [comment]
I've seen the documentation. However, I believe it is not good/useful to download the entire Pippo repository just to make a quick application. I'm trying to propose something easier like run this script and magically is running a simple application

**Comment by decebals** [comment]
> I believe it is not good/useful to download the entire Pippo repository just to make a quick application.

You don`t download the entire Pippo repo (in documentation wrote that first step is Optional). Only run the mvn command with your custom data (application name, groupId, ...). Ofen I use this approach to create new projects for testing (run in isolation an issue for example). I wrap mvn comand in a script , I extract the custom data in variables and I run the script from command line. I think that it's very easy.

**Comment by MateusGabi** [comment]
I tested it here, and worked fine 💯 . I'm sorry

**Comment by decebals** [comment]
@MateusGabi No problem. You are welcome.
