### ISSUE TITLE
Sending index.html as static files

### ISSUE THREAD

**Issue by mustafaakin** [decebals/pippo#391]
Hi, nice project, definetely love it. With Guice+jdbc wrapper it defintely replaces Spring for me. However, I am having an issue of sending `index.html` with static paths configured. My web app is completely Angular 4, no templates and stuf, I use Pippo as a REST backend. I tried the following  but when I go to `http://localhost:8338` it returns `404` I need to type `index.html` explicitly. As far as I see from code, only `DirectoryHandler` handles it, but I cannot see how it is used anywhere. 

```java
pippo.addPublicResourceRoute("/");
pippo.addFileResourceRoute("/", "src/main/web");
pippo.addResourceRoute(new FileResourceHandler("/", "src/main/web/index.html"));
```

And my dir layout: (not double index.html, I tried the above code for each line)

```bash
➜  main tree resources web
resources
├── WEB-INF
├── application.properties
├── log4j.properties
└── public
    └── index.html
web
└── index.html

2 directories, 4 files
```

**Comment by mustafaakin** [comment]
For my dev purposes, I did the following: 

```java
        GET("/", (RouteContext context) -> {
            try {
                String filepath = "src/main/resources/public/index.html";
                String html = IoUtils.toString(new FileInputStream(filepath));
                context.send(html);
            } catch (IOException e) {
                throw new PippoRuntimeException(e);
            }

        });

```

But in prod, having a propoer cache like other static files would be great, thats why I am asking for a solution that is in Pippo.

**Comment by decebals** [comment]
In the end of one of my [comment](https://github.com/decebals/pippo/pull/279#issue-158442384) I wrote how I serve an `index.html` from the root of my application.
The variant described by you in your second comment is OK. You can add very easy support for cache (keep a `String indexCache` variable in application or the route handler that is used for `GET /` and check if your application is started in prod mode` to read/write from/to indexCache).

**Comment by mustafaakin** [comment]
Sure, but it can be nice if it is included in the library. If you plan for it, I can make a PR if you wish. Really love your project.

**Comment by decebals** [comment]
>  but it can be nice if it is included in the library

I don't know the best approach to implement this. You can share with us your idea about a possible implementation (with snippet code).

**Comment by decebals** [comment]
Now you can use [IoUtils#getResourceAsString](https://github.com/pippo-java/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/util/IoUtils.java#L110).

**Comment by decebals** [comment]
@mhagnumdw 

> Please, make this method static for reuse. I make a pull request, ok?

Excellent observation. Please create a PR or an issue (for changelog reference)  and apply yourself the PR (commit the modification on master) :smile:.

Thanks!
