### ISSUE TITLE
Add ability to access underlying tomcat instance when using TomcatServer

### ISSUE THREAD

**Issue by jonnymatts** [decebals/pippo#392]
Hi,

I am using pippo-tomcat in one of my projects and I need to be able to add a valve to the tomcat pipeline. I could do this if I had access to the Tomcat instance held by TomcatServer: after it was created but before it starts.

I have done something similar before with the JettyServer as it had the method `createServer` which I could override and extract the server from.

Thanks

**Comment by jonnymatts** [comment]
Thanks!

**Comment by decebals** [comment]
You're welcome. You can use the SNAPSHOT version until the next release.
