### ISSUE TITLE
Pippo integration with Security framework

### ISSUE THREAD

**Issue by codematix** [decebals/pippo#393]
I wanted to know if there are plans to integrate any security framework with Pippo. Possible candidates could be:

1. pac4j
2. Apache Shiro

Or... any other framework

**Comment by decebals** [comment]
I don't plan to add new module in the near future in Pippo. I wish to consolidate, test and document what already exists. In the same time, I am happy to help new initiatives. So, if you are interested in a security framework please create a project, share this project with us on Github and I am ready to contribute. I am curios to see a security framework integrated in Pippo, not something complicated/big.

**Comment by decebals** [comment]
A security framework should resolve two problems:
- authentication
- authorization

I prefer something light, extensible, easy to integrate in Pippo (maybe not complete from the features point of view). In the end, Pippo is the land of choice for people that write small and medium application (from complexity point of view) so in this context I prefer libraries in same note.

**Comment by codematix** [comment]
I am toying with the idea of building an integration for [pac4j](http://www.pac4j.org/). Seems like a popular choice by other micro frameworks like Ratpack or Jooby.

So I have a few questions:
1. Any thoughts or preferences about pac4j?
2. Would you be willing to add it as part of Pippo (as in a `pippo-security-parent` and `pippo-pac4j`?

**Comment by decebals** [comment]
@codematix 
> Any thoughts or preferences about pac4j?

I don't know to much about pac4j so I cannot tell you to much.

> Would you be willing to add it as part of Pippo (as in a pippo-security-parent and pippo-pac4j)?

In the first phase I prefer a new repo, something like `pippo-pac4j`. A new module in Pippo means supplementary code to maintain and we should concentrate our efforts on core.

I am curios to know how other Pippo users resolve the security aspect in their applications. Maybe we can choose/adopt something that it's already integrated with Pippo.

**Comment by codematix** [comment]
> In the first phase I prefer a new repo, something like pippo-pac4j. A new module in Pippo means supplementary code to maintain and we should concentrate our efforts on core.
>
> I am curios to know how other Pippo users resolve the security aspect in their applications. Maybe we can choose/adopt something that it's already integrated with Pippo.

Yes it would be great to hear from other Pippo users as to how they have managed to implement the security aspect into their applications and also what their preference would be for a first-class security integration with Pippo.

About my experience, I have been using Spring Framework and the Spring Security modules for my applications. It has served us well in the past by integrating with most authenication/authroization systems.

We are trying to build some new products in our current project and as part of that, we are closely evaluating Pippo. We are very pleased with what we see in Pippo and want to see if we can use a off-the-shelf security framework like pac4j/Shiro can be integrated with Pippo.

I would request the Pippo community to voice out their preference/thoughts of a security framework integration with Pippo.

**Comment by decebals** [comment]
Maybe it's useful http://www.pac4j.org/docs/how-to-implement-pac4j-for-a-new-framework.html.

**Comment by codematix** [comment]
@decebals Yes that is what I am using to build the integration along with referring to some other integrations.

Please consider contributing to my attempt at this - [pippo-pac4j](https://github.com/codematix/pippo-pac4j)

**Comment by mhagnumdw** [comment]
> @decebals I am curios to know how other Pippo users resolve the security aspect in their applications. Maybe we can choose/adopt something that it's already integrated with Pippo.

Below my **simple** contribution.

Authentication controllers (www and web services) I did not put in because they had a lot of specific logic, but they followed the basic flow of validating username and password. The controller to "log in" to web services (ie getting JWT) validates username and password, and if valid returns the token (JWT). The next requests for web services must be made through the token (JWT).

**AuthenticationFilter**: check if the user is authenticated at each request (www) (screen requests);
**WebServiceAuthenticationFilter**: check if JSON Web Token (JWT) is valid for web services requests;
**RequireRole**: annotation for Pippo to intercept access to the method and check the authorization;
**RoleHandler**: business logic to check authorization;
**CustomRouteContext**: to force controller methods to define some of the authorization annotations;

```java
public class PippoApplication extends ControllerApplication {
	protected void onInit() {
		ANY("/p/.*", new AuthenticationFilter()); // Check if the user is authenticated at each request (www)
		ANY("/ws/p/.*", new WebServiceAuthenticationFilter()); // Check if (JWT) JSON Web Token is valid for web services requests
	}
}

/////

/**
 * '/p/.*'
*/
public class AuthenticationFilter implements RouteHandler {

    @Override
    public void handle(RouteContext routeContext) {
        Pair<Boolean, String> loggedAndValidAndStatus = SecurityHelper.loggedAndValid(routeContext);
        boolean loggedAndValid = loggedAndValidAndStatus.getFirst();
        if (loggedAndValid) {
            routeContext.next();
        } else {
            String status = loggedAndValidAndStatus.getSecond();
            routeContext.setSession(Constantes.KEY_SESSION_ORIGINAL_DESTINATION, routeContext.getRequest().getApplicationUriWithQuery());
            routeContext.flashWarning(status);
            routeContext.redirect(Constantes.PATH_LOGIN);
        }
    }

}

/////

/**
 * '/ws/p/.*'
 * Filter for web services to check if the JSON Web Token of the requester is valid.
 * <p>
 * The token must be passed in the request header in the attribute {@link JsonWebTokenHelper#ATTR_JSON_WEB_TOKEN}.
 * </p>
 */
public class WebServiceAuthenticationFilter implements RouteHandler {

    private static final Logger log = LoggerFactory.getLogger(WebServiceAuthenticationFilter.class);

    @Override
    public void handle(RouteContext routeContext) {
        String jwtString = JsonWebTokenHelper.getJsonWebToken(routeContext);
        try {
            if (StringUtils.isBlank(jwtString)) {
                throw new MyException(JsonWebTokenHelper.ATTR_JSON_WEB_TOKEN + " attribute in header");
            }

            final String username;
            try {
                username = JsonWebTokenHelper.getUsername(jwtString);
            } catch (Exception e) {
                throw new MyException(JsonWebTokenHelper.ATTR_JSON_WEB_TOKEN + " invalid token");
            }

            if (StringUtils.isBlank(username)) {
                throw new MyException(JsonWebTokenHelper.ATTR_JSON_WEB_TOKEN + " user not defined in the token");
            }

            UserService userService = GuiceInjector.get().getInstance(UserService.class);
            User user = userService.getByUsername(username);
            if (user == null) {
                throw new MyException(JsonWebTokenHelper.ATTR_JSON_WEB_TOKEN + " no user for the informed token");
            }

            String jwtBase64Key = user.getJwtBase64Key();
            if (StringUtils.isBlank(jwtBase64Key)) {
                throw new MyException(JsonWebTokenHelper.ATTR_JSON_WEB_TOKEN + " need to sign in to get the token");
            }

            JsonWebTokenHelper.validateJWT(jwtString, jwtBase64Key);

            SecurityHelper.setLoggedUser(routeContext, user);

            routeContext.next();
        } catch (MalformedJwtException e) { // string is not a valid JWS
            throw new MyException(JsonWebTokenHelper.ATTR_JSON_WEB_TOKEN + " in invalid format.");
        } catch (SignatureException e) { // JWS signature validation fails
            throw new MyException(JsonWebTokenHelper.ATTR_JSON_WEB_TOKEN + " with invalid signature.");
        } catch (ExpiredJwtException e) { // Se o token estiver expirado
            throw new MyException(JsonWebTokenHelper.ATTR_JSON_WEB_TOKEN + " expired.");
        } catch (MyException e) {
            throw e;
        } catch (Exception e) { // Other
            throw new MyException(JsonWebTokenHelper.ATTR_JSON_WEB_TOKEN + " impossible to validate", e);
        } finally {
            if (routeContext.hasSession()) {
                routeContext.invalidateSession();
            }
        }
    }


/////

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@Interceptor(RoleHandler.class)
public @interface RequireRole {

    String roleName() default "";

    String description() default "";

}

/////

public class RoleHandler implements RouteHandler {

    private static final Logger log = LoggerFactory.getLogger(RoleHandler.class);

    @Override
    public void handle(RouteContext routeContext) {
        log.trace("RoleHandler.handle");

        Method method = PippoJarvisUtils.getMethod(routeContext.getRoute());

        log.debug("Checking authorization for '{}'", LangUtils.toString(method));

        RequireRole requireRole = method.getAnnotation(RequireRole.class);

        final String roleName = requireRole.roleName();
        User user = SecurityHelper.getUsuarioLogado(routeContext);

        UserService userService = GuiceInjector.get().getInstance(UserService.class);

        boolean authorized = userService.authorize(user, roleName);
        if (!authorized) {
            throw new MyException("You are not authorized to take the action: " + roleName, "/p/home", true);
        }

        // here the user can access the method
    }

}

/////

public class CustomRouteContext extends DefaultRouteContext {

    protected CustomRouteContext(Application application, Request request, Response response, List<RouteMatch> routeMatches) {
        super(application, request, response, routeMatches);
    }

    // Requires that all controller methods have at least one of the authorization annotations
    // TODO: The annoying thing to intercept here is that here are not only the routes of Controllers, but also of Filters and other
    @Override
    protected void handleRoute(Route route) {
        if (ControllerRouteHandler.class.isAssignableFrom(route.getRouteHandler().getClass())) {
            Method method = PippoJarvisUtils.getMethod(route);
            if (method.isAnnotationPresent(Public.class) || method.isAnnotationPresent(RequireRole.class)) {
                super.handleRoute(route);
            } else {
                throw new MyException("Need to apply security policy on " + LangUtils.toString(method) + ".", "/p/home", true);
            }
        } else {
            super.handleRoute(route);
        }
    }

}

/////

@AutoService(RouteContextFactory.class)
public class CustomRouteContextFactory extends DefaultRouteContextFactory {

    @Override
    public CustomRouteContext createRouteContext(Application application, Request request, Response response, List<RouteMatch> routeMatches) {
        return new CustomRouteContext(application, request, response, routeMatches);
    }

}

/////

public final class SecurityHelper {

    public static Pair<Boolean, String> loggedAndValid(RouteContext routeContext) {
        if (SecurityHelper.userLoggedIn(routeContext)) {
            String clientIpSession = getIpUsuarioLogado(routeContext);
            String clientIp = routeContext.getRequest().getClientIp();
            if (clientIp.equals(clientIpSession)) { // If IP has not changed
                return new Pair<Boolean, String>(true, "Authenticated and valid user.");
            } else { // If IP has changed, re-login
                return new Pair<Boolean, String>(false, "Your IP has changed. Authentication required again.");
            }
        } else { // If unauthenticated user
            return new Pair<Boolean, String>(false, "Authentication required.");
        }
    }

}

```

**Comment by decebals** [comment]
@mhagnumdw Your code looks good. The code is easy to understand and follow.
The part with `CustomRouteContext` is a little bit tricky. For example I don't understand the utility of this class.
Take an example:
```java
if (method.isAnnotationPresent(Public.class) || method.isAnnotationPresent(RequireRole.class)) {
    ...
}
``` 
I see here a simplification, if the web method  is not annotated with `@RequireRole` then, by default, the web method is public (no security constraint). Again, I feel that `CustomRouteContext` is not needed.

**Comment by mhagnumdw** [comment]
> if (method.isAnnotationPresent(Public.class) || method.isAnnotationPresent(RequireRole.class)) {
>     ...
> }
> I see here a simplification, if the web method is not annotated with @RequireRole then, by default, the web method is public (no security constraint). Again, I feel that CustomRouteContext is not needed.
> 

@decebals You're right. I'm in the process of migrating from Pippo 1.1.0 to 1.5.0 and this is a remnant code.

**Comment by decebals** [comment]
@codematix Thanks for your contribution!
