### ISSUE TITLE
getResponse().status(200) return 404 code

### ISSUE THREAD

**Issue by skaarr** [decebals/pippo#394]
I don't know why, but getResponse().status(200); will return 404. I think this is wrong behavior and returned status should be 200. Am I correct?

I created simple test here https://github.com/skaarr/pippo-status

**Comment by codematix** [comment]
This feels like a bug in `ro.pippo.controller.ControllerRouteHandler` in the following lines:

https://github.com/decebals/pippo/blob/96ba7bccb2499ba2049a463eb8a0ce6f40eaa5a0/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/ControllerRouteHandler.java#L135-L155

Looks like we may need to support a `Void` return type as an empty response with specified status code.

@decebals Your thoughts?

**Comment by decebals** [comment]
I don't know what to say.

![image](https://user-images.githubusercontent.com/1248311/30761180-0056c876-9fe6-11e7-8826-0f9daac6a97e.png)

I think that it's 50% bug and 50% bad use case :smile:.
It's hard for me to find a real use case that returns only the status code in response without data.
I will fix it.

**Comment by codematix** [comment]
Although I second your opinion on the use case, I have seen a lot of these in the wild.

**Comment by skaarr** [comment]
I use this in rest api. For example POST request:
```
String url = routeContext.uriFor(FormController.class, "findOne", parameters);
getResponse().header("Location " + url).status(201);
```
or DELETE request
```
getResponse().status(204);
```

**Comment by decebals** [comment]
@skaarr If you encounter other problem, please let me know. The controller modules has redesigned [recently](https://github.com/decebals/pippo/pull/341), and from this reason they are possibilities to have small issues.

**Comment by skaarr** [comment]
@decebals Ok. thank you!
