### ISSUE TITLE
How to use path parameters encoded in WebSocket url ?

### ISSUE THREAD

**Issue by kant111** [decebals/pippo#395]
currently there seems to be no way to specify path parameters in the WebSocket URL in undertow or jetty. I currently use undertow. 

My use case is I have list of names and I would like to create a generic route that will take "name" as a path parameter so I can just have one handler for the whole list of names I got. 

For example I want to be able to do something like below:

```
addWebSocket("/hello/{name}", (webSocketContext, message) -> {
    try {
        somehow get the value that is passed in for ":name" here
        webSocketContext.sendMessage(message);
    } catch (IOException e) {
        e.printStackTrace();
    }
});
```
To elaborate even further, I am trying to broadcast a messages for all the clients that are listening on specific endpoint. so if I have something like below I wan to be able to broadcast all messages that have a connection opened on "/hello/foo" endpoint. so here my "{name}" = "foo" but I can pass anything from the list of names I have in which case I want to be able to pass name as path parameter.

```
addWebSocket("/hello/foo", (webSocketContext, message) -> {
    try {
        so ":name" = "foo" here
        webSocketContext.sendMessage(message);
    } catch (IOException e) {
        e.printStackTrace();
    }
});
```

**Comment by decebals** [comment]
I will come with a solution.

**Comment by kant111** [comment]
@decebals Appreciate it!!

**Comment by decebals** [comment]
I propose as solution https://github.com/decebals/pippo/pull/397 but I don't know when I have some time to finish the PR.

**Comment by kant111** [comment]
@decebals The commit looks good! What else needs to be done to finish the PR?

**Comment by decebals** [comment]
@kant111 We should: 
- expose the path parameters (we have these information already), add new useful methods in WebSocketContext like `getQueryString()`, `getSession()`, `getParameterNames()`, `getParameterValue()`.
- add DefaultUriMatcherTest
- review new code (classes/interfaces names, integration with existed code - DefaultRouter, ...)

**Comment by decebals** [comment]
The final solution:
```java
addWebSocket("/ws/chat/{roomId}", (webSocketContext, message) -> {
    String roomId = webSocketContext.getPathParameter("roomId").toString();
    System.out.println("roomId = " + roomId);
});
```

I will upgrade [demo](https://github.com/decebals/pippo-demo/blob/master/pippo-demo-websocket/src/main/java/ro/pippo/demo/websocket/WebSocketApplication.java) application very soon.
