### ISSUE TITLE
ErrorHandler not properly working with Controllers and CheckedExceptions

### ISSUE THREAD

**Issue by Timmeey** [decebals/pippo#396]
I'm using pippo-core/controller 1.5.0
Adding ErrorHandlers for checked exceptions thrown by Controller methods does not work as expected.
When i say "Controller Method" i mean a Method that is called by a http request. For example:

```java
@GET("/stations/{station}")
@Produces(Produces.JSON)
public Station getStation(@Param("station") final String station) throws FooException {
    return this.stations.get(station);
}
```

## Expected behavior:
Adding an ErrorHandler for `FooException.class` should result in that ErrorHandler being used if a Controller Method throws an Exception of Type `FooException.class`.

## Actual behavior:
ErrorHandler for `FooException.class` is not used

## Steps to reproduce
Add a ErrorHandler for `FooException.class` that writes a log/does something visible
Let a Controller method throw an Instance of `FooException.class`
Check and see that the ErrorHandler for `FooException.class` was not called

In the logs it just shows
```
ro.pippo.core.PippoRuntimeException: de.timmeey.oeffiwatch.exception.AmbigiuousStationNameException
```

The problem seems to be that all non-RuntimeExceptions thrown by controller methods get wrapped in a `PippoRuntimeException` inside the `ControllerRouteHandler#handleDeclaredThrownException` before bubbling up further to the `DefaultErrorHandler`.

The solution would seem handle `PippoRuntimeException` as a special Case in `DefaultErrorHandler#handle()` and try to handle the nested exception the given Exception is a PippoRuntimeException and the nested throwable is a exception.

**Comment by decebals** [comment]
A [quickstart](http://www.pippo.ro/dev/quickstart.html) project is welcome. I want to see how you use the error handler (http://www.pippo.ro/doc/error-handling.html).

**Comment by Timmeey** [comment]
Sure. I just created one very simple example real quick
https://github.com/Timmeey/pippo-quickstart-demo/blob/master/src/main/java/de/timmeey/bastel/DemoController.java

There once you call /demo you get a 500 response instead of the expected 404 (whcih is declared in the exceptionHandler in the Controller constructor)

**Comment by decebals** [comment]
I think that we can close this issue.
