### ISSUE TITLE
[Question] Access controller method from RouteContext

### ISSUE THREAD

**Issue by codematix** [decebals/pippo#399]
Is there any way to access the controller method from `RouteContext`?

As you may know, I am writing an integration for Pippo with the pac4j security framework. I wanted to provide a way by which a URL "security filter" can get access to the controller method which would be invoked for the request and apply authentication/authorization if the controller method was decorated with a certain annotation or not.

**Comment by decebals** [comment]
I feel that correct approach is to implement a security annotation and an interceptor.
See:
- https://github.com/decebals/pippo/pull/341#issuecomment-272658749
- https://github.com/decebals/pippo-demo/blob/master/pippo-demo-controller/src/main/java/ro/pippo/demo/controller/LoggingHandler.java
- https://groups.google.com/forum/#!topic/pippo-java/ICAaSp8vu9s

> Is there any way to access the controller method from RouteContext?
```java
Route route = routeContext.getRoute();
Method method = route.getAttribute("__controllerMethod");
```

**Comment by codematix** [comment]
Thanks @decebals, I went through the links and they were immensely useful. I would strongly urge you to bring some of the contents in those posts (esp https://github.com/decebals/pippo/pull/341#issuecomment-272271689) into the main documentation site.

I think it is features like these that make Pippo unique and powerful. If this content were to be on the main site, it might help/encourage more developers to seriously consider Pippo for adoption in their projects.

**Comment by decebals** [comment]
It's an issue created by me on pippo-site project, https://github.com/decebals/pippo-site/issues/56. My big problem is the time. A PR is very welcome.

**Comment by codematix** [comment]
> My big problem is the time.

Thats the story of all our lives @decebals :-). Thanks for all your efforts and contribution.
