### ISSUE TITLE
Can't complete request processing in handler

### ISSUE THREAD

**Issue by skaarr** [decebals/pippo#401]
Here is the sample https://github.com/skaarr/pippo-handler

I try create CORS handler and I want send accepted status from handler if request method is "OPTIONS". But now it returns 404.

Am I doing something wrong?

**Comment by decebals** [comment]
![image](https://user-images.githubusercontent.com/1248311/31298594-8bc11e76-aaf3-11e7-961e-8a0ec25ed5d2.png)

I don't understand where is the problem?

**Comment by skaarr** [comment]
Please run included test

**Comment by skaarr** [comment]
![screenshot-2017-10-07-1128x129](https://user-images.githubusercontent.com/6853493/31304742-c9d1c51a-ab31-11e7-990c-84dbf756fc1c.png)
There is the problem

**Comment by skaarr** [comment]
My bad. Route pattern for handler should be `/.*`

All is ok.
