### ISSUE TITLE
Any syntax error in freemarker template results in "PippoRuntimeException: Recursion in error handler" exception 

### ISSUE THREAD

**Issue by denbkh** [decebals/pippo#410]
Steps to reproduce:

1. clone pippo-demo-basic
1. add any syntax error to pippo-demo-basic/src/main/resources/templates/hello.ftl
1. run BasicDemo.main()
1. open http://localhost:8338/template
1. you will get http 500 exception with message "ro.pippo.core.PippoRuntimeException: Recursion in error handler"

But it should be "ro.pippo.core.PippoRuntimeException: freemarker.core.ParseException: Syntax error in template "hello.ftl" in line X, column Y"

**Comment by decebals** [comment]
Thanks for the detailed. I will take a look and I will come with a fix.

**Comment by decebals** [comment]
Fix it :smile:.
Good catch. Thanks!

I updated the SNAPSHOT version with this fix.

**Comment by denbkh** [comment]
The same problem exists if you have (1) CSRF token mismatch and after that (2) forbidden template not found... This chain of exceptions results in "Recursion in error handler".
Do you really think that increasing the "depth" counter is the proper fix? 
With such design of recursion detection maybe increasing the counter to 100 might help ;)

**Comment by decebals** [comment]
> The same problem exists if you have (1) CSRF token mismatch and after that (2) "forbidden" template not found... This chain of exceptions results in "Recursion in error handler".

Did you tested with the last modifications?

> Do you really think that increasing the "depth" counter is the proper fix?
With such design of recursion detection maybe increasing the counter to 100 might help ;)

I don't have other idea for the moment. I will try to see if I find something new. Any help is welcome (other idea or unit tests that replicate the problem).

**Comment by denbkh** [comment]
> Did you tested with the last modifications?
Yes, I have tested it and it fixes the initial case. 
But if I have a longer chain of exceptions I still receive the "Recursion in error handler". I got one with CSRF token mismatch and incorrectly named template for rendering "forbidden" errors.

**Comment by decebals** [comment]
> and after that (2) "forbidden" template not found...

> But if I have a longer chain of exceptions I still receive the "Recursion in error handler"

Can you add more details about your context (eventually a [quickstart](http://www.pippo.ro/dev/quickstart.html)) because I want to reproduce the problem on my machine.

**Comment by denbkh** [comment]
Create custom error handler:
```
public class ExampleErrorHandler extends DefaultErrorHandler {
        public ExampleErrorHandler(Application application) {
            super(application);
        }

        @Override
        protected String getTemplateForStatusCode(int statusCode) {
            return "example";
        }
    }
```
Create application 
```
public class ExampleApplication extends Application {
    @Override
    protected void onInit() {
        setErrorHandler(new ExampleErrorHandler(this));
        ANY("/example", new CSRFHandler());
        POST("/example", routeContext -> routeContext.send("Hello World"));
    }
}
```
Run curl:
```
curl -i "http://localhost:8080/example" -H "Host: localhost:8080" --data ""
````

Result: `PippoRuntimeException: Recursion in error handler`
Expected result: `freemarker.template.TemplateNotFoundException: Template not found for name "example.ftl"` or `ro.pippo.core.StatusCodeException: Illegal request, no '_csrf_token'`

**Comment by decebals** [comment]
I investigated the new problem. It's not about the counter. It's a circular call between render and renderHtml in DefaultErrorHandler.

Just a curiosity related to you solution with ExampleErrorHandler. Why you create a new class `ExampleErrorHandler` and override `getTemplateForStatusCode`? You already have a template name for majority of common status code in `DefaultErrorHandler`, all you need to do is to put a new template file with that name in `templates` directory and modify the content of the template.

**Comment by denbkh** [comment]
> Just a curiosity related to you solution with ExampleErrorHandler. Why you create a new class ExampleErrorHandler and override getTemplateForStatusCode?

This example was created mostly for illustrative purposes. However, it could be useful to create one template for all errors.
The situation will be the same if you make an syntax error in the "403forbidden.ftl" template.
