### ISSUE TITLE
Adjusting GsonEngine configuration is overly hard (or even impossible?)

### ISSUE THREAD

**Issue by bentolor** [decebals/pippo#414]
The default GsonEngine assume some quite opinonated Settings i.e. about Time-based date Types. It [assumes `java.util.Date` is a timestamp but `java.sql.Date` is a full date](https://github.com/decebals/pippo/blob/master/pippo-content-type-parent/pippo-gson/src/main/java/ro/pippo/gson/GsonEngine.java#L68)

I'm in need to adjust this: my `java.util.Date`s are Dates, note Times.

My naive implementation looks like this:

````
public class MyApp extends ControllerApplication {
    protected void onInit() {
        registerContentTypeEngine(IsoDateGsonEngine.class);
    }
}

/**
 * Dirty hack to adjust Pippos default configuration for Gson.
 */
public class IsoDateGsonEngine extends GsonEngine {

    private final Gson gson;

    public IsoDateGsonEngine() {
        gson = new GsonBuilder().registerTypeAdapter(Date.class, new ISO8601DateTypeAdapter()).create();
    }

    public String toString(Object object) {
        return gson.toJson(object);
    }

    public <T> T fromString(String content, Class<T> classOfT) {
        return gson.fromJson(content, classOfT);
    }
}
````

Boy – am I wrong. This does not work, because [the Service Locator infrastructure in `Application`](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Application.java#L105) finds the [`GsonInitializer`](https://github.com/decebals/pippo/blob/master/pippo-content-type-parent/pippo-gson/src/main/java/ro/pippo/gson/GsonInitializer.java) and adds the default configuration on its own. Furthermore there is no way to _replace_ or _remove_ a preexisting content type handler. The [code actively ignores that](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/ContentTypeEngines.java#L102).

Any idea how to tackle that?

**Comment by decebals** [comment]
Is https://github.com/decebals/pippo/issues/274 what you are looking for?

**Comment by bentolor** [comment]
@decebals Yes, `getContentTypeEngines().setContentTypeEngine(new IsoDateGsonEngine());` enables me to use a custom configured Gson engine.
