### ISSUE TITLE
Running CrudNgApplication as WAR

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#70]
I try to run CrudNgApplication from pippo-demo as WAR on a tomcat 7. The problem is that I encountered a strange issue:
- sometime (in fact in most cases) in the console browser I see:

> Resource interpreted as Stylesheet but transferred with MIME type application/octet-stream: "http://localhost:8080/webjars/bootstrap/3.3.1/css/bootstrap.min.css".
login:41 Resource interpreted as Script but transferred with MIME type application/octet-stream: "http://localhost:8080/webjars/jquery/1.11.1/jquery.min.js".
login:42 Resource interpreted as Script but transferred with MIME type application/octet-stream: "http://localhost:8080/webjars/bootstrap/3.3.1/js/bootstrap.min.js".
login:43 Resource interpreted as Script but transferred with MIME type application/octet-stream: "http://localhost:8080/webjars/angularjs/1.3.6/angular.min.js".

and of course that I cannot use the webjars defined in head
- sometime I see an error related to transfer encoding chunked (I will try to catch and display the error)

**Comment by decebals** [comment]
The second error is:
> ERR_INVALID_CHUNKED_ENCODING

This error appears only in Chrome.

**Comment by balamaci** [comment]
I see the mimetype is set correctly at the point of ClasspathResourceHandler:123 however 
however I think it's being rewritten in
Response: public void resource(InputStream input) {
           if (isHeaderEmpty(HttpConstants.Header.CONTENT_TYPE)) {
            header(HttpConstants.Header.CONTENT_TYPE, HttpConstants.ContentType.APPLICATION_OCTET_STREAM);
        }
}
because the condition isHeaderEmpty might evaluate to true on Tomcat.

**Comment by decebals** [comment]
tested on tomcat 7.0.57
