### ISSUE TITLE
RFC: Split pippo-demo in multiple module

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#73]
The problem is that if I want to create an WAR for CrudNgApplication (an example), this WAR file has around of 20MB because I put all demo jars (jetty, spring, trimou, ...). Probably the real size is around of 200KB. I think that it's very important to show that a pippo application has a small footprint.
My intention is to split pippo-demo in multiple maven module (a folder, an application and a pom.xml for each module).
The new structure could be: 
```
pippo-demo
   pippo-demo-simple
   pippo-demo-crud
   pippo-demo-crudng
   pippo-demo-controller
   pippo-demo-upload
   pippo-demo-spring
   pippo-demo-guice
   pippo-demo-validation
```

It's a problem with pippo-template that already contains multiple application (one for each template engine).

Do you see other options?

**Comment by gitblit** [comment]
The real size will definitely be larger than 200KB but certainly less than 20 MB.  :)

Either we should have a `pippo-demo-template` with all engines linked or move each engine demo to the engine module.  Several of the demos have alot of code duplication.  Perhaps `pippo-demo` could contain common code.  Honestly, it doesn't make a big difference to me how the demo code gets structured.  Pick one that makes sense to you and run with it.

**Comment by decebals** [comment]
In `pom.xml` for `pippo-demo` I created two profiles:
- main
- war

The `main` profile is the default. This profile set `packaging.type` property to __jar__ and add `pippo-jetty` as dependency.
The `war` profile set `packaging.type` property to __war__. To activate this profile you must run mvn command with `-Pwar` (for example `mvn -Pwar clean package`)

**Comment by decebals** [comment]
I created a [linux script file](https://gist.github.com/decebals/9f7e57e42b705be8a092#file-run-pippo-demo-sh) that help me to run a demo module into an apache tomcat container.
Maybe it's useful for someone.
