### ISSUE TITLE
Remove ThreadContext (maybe temporary)

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#97]
I see that ThreadContext is no longer used so I prefer to remove it.
I see that many java web frameworks use ThreadLocal (Spring MVC, Wicket, Vaadin, Play Framework - see thread local context propagation). It's not safe but help a lot. I dislike to pass as parameter a context object in 80% of framework methods.

**Comment by gitblit** [comment]
There are two legitimate use-cases I can think of for `ThreadLocal`.

1. Consuming some library where your app calls into the library and executes some method you also maintain somewhere in the middle of the library execution.  You can't necessarily provide all necessary objects when calling into the library so a `ThreadLocal` is very useful.
2. Method interceptors.  Those may require state that can't be supplied as an argument.

While I'm not currently using `ThreadContext`, it could have considerable value for use-case 2.  I think you should keep it and a `RouteContext` object.
